/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/
// ----------------------------------------------------------------
//  This file was generated from the XML error message source.
//  so do not edit this file directly!!
// ----------------------------------------------------------------

#include <xercesc/util/XercesDefs.hpp>

XERCES_CPP_NAMESPACE_BEGIN

const unsigned int CatId_XMLErrs = 1;
const unsigned int CatId_XMLValid = 2;
const unsigned int CatId_XMLExcepts = 3;
const unsigned int CatId_XMLDOMMsg = 4;

XERCES_CPP_NAMESPACE_END

