//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
// SWI Capability tests
PRINT Run all SWIS capability tests

LOAD_SUITE aprcaptestframework


//! @SYMTestCaseID 		API-SEC-SWI-CapTests-I-0001
//! @SYMTestCaseDesc 		Runs the whole suite of test cases for SWI interfaces. Both negtive and positive tests are included
//! @SYMTestPriority 		High
//! @SYMTestStatus		3. Released
//! @SYMTestActions 		Tests IPC calls from different capabilities
//! @SYMTestExpectedResults 	KErrPermissionDenied received on calls which should fail
//! @SYMDevelopedForRelease 	Yankee


START_TESTCASE API-SEC-SWI-CapTests-I-0001

RUN_UTILS MkDir c:\tswi\
RUN_UTILS MkDir c:\tswi\swicaptests
RUN_UTILS MkDir c:\tswi\swicaptests\data
RUN_UTILS CopyFile z:\tswi\swicaptests\data\testdoc.txt c:\tswi\swicaptests\data\testdoc.txt
RUN_TEST_STEP 100 aprcaptestframework RunThoroughCapabilityChecks z:\tswi\swicaptests\scripts\swicaptests.ini swicaptests

END_TESTCASE API-SEC-SWI-CapTests-I-0001
