/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
/* Automatically generated.  Do not edit */
/* See the mkopcodec.awk script for details. */
#if !defined(SQLITE_OMIT_EXPLAIN) || !defined(NDEBUG) || defined(VDBE_PROFILE) || defined(SQLITE_DEBUG)
const char *const sqlite3OpcodeNames[] = { "?",
 /*   1 */ "ReadCookie",
 /*   2 */ "AutoCommit",
 /*   3 */ "Found",
 /*   4 */ "NullRow",
 /*   5 */ "MoveLe",
 /*   6 */ "Variable",
 /*   7 */ "Pull",
 /*   8 */ "RealAffinity",
 /*   9 */ "Sort",
 /*  10 */ "IfNot",
 /*  11 */ "Gosub",
 /*  12 */ "NotFound",
 /*  13 */ "MoveLt",
 /*  14 */ "Rowid",
 /*  15 */ "CreateIndex",
 /*  16 */ "Not",
 /*  17 */ "Push",
 /*  18 */ "Explain",
 /*  19 */ "Statement",
 /*  20 */ "Callback",
 /*  21 */ "MemLoad",
 /*  22 */ "DropIndex",
 /*  23 */ "Null",
 /*  24 */ "Int64",
 /*  25 */ "LoadAnalysis",
 /*  26 */ "IdxInsert",
 /*  27 */ "VUpdate",
 /*  28 */ "Next",
 /*  29 */ "SetNumColumns",
 /*  30 */ "MemInt",
 /*  31 */ "Dup",
 /*  32 */ "Rewind",
 /*  33 */ "Last",
 /*  34 */ "MustBeInt",
 /*  35 */ "MoveGe",
 /*  36 */ "String",
 /*  37 */ "VFilter",
 /*  38 */ "ForceInt",
 /*  39 */ "Close",
 /*  40 */ "AggFinal",
 /*  41 */ "AbsValue",
 /*  42 */ "RowData",
 /*  43 */ "IdxRowid",
 /*  44 */ "MoveGt",
 /*  45 */ "OpenPseudo",
 /*  46 */ "Halt",
 /*  47 */ "MemMove",
 /*  48 */ "NewRowid",
 /*  49 */ "IdxLT",
 /*  50 */ "Distinct",
 /*  51 */ "MemMax",
 /*  52 */ "Function",
 /*  53 */ "IntegrityCk",
 /*  54 */ "FifoWrite",
 /*  55 */ "NotExists",
 /*  56 */ "VDestroy",
 /*  57 */ "MemStore",
 /*  58 */ "IdxDelete",
 /*  59 */ "Vacuum",
 /*  60 */ "Or",
 /*  61 */ "And",
 /*  62 */ "If",
 /*  63 */ "Destroy",
 /*  64 */ "AggStep",
 /*  65 */ "IsNull",
 /*  66 */ "NotNull",
 /*  67 */ "Ne",
 /*  68 */ "Eq",
 /*  69 */ "Gt",
 /*  70 */ "Le",
 /*  71 */ "Lt",
 /*  72 */ "Ge",
 /*  73 */ "Clear",
 /*  74 */ "BitAnd",
 /*  75 */ "BitOr",
 /*  76 */ "ShiftLeft",
 /*  77 */ "ShiftRight",
 /*  78 */ "Add",
 /*  79 */ "Subtract",
 /*  80 */ "Multiply",
 /*  81 */ "Divide",
 /*  82 */ "Remainder",
 /*  83 */ "Concat",
 /*  84 */ "Insert",
 /*  85 */ "Negative",
 /*  86 */ "VBegin",
 /*  87 */ "BitNot",
 /*  88 */ "String8",
 /*  89 */ "IdxGE",
 /*  90 */ "OpenEphemeral",
 /*  91 */ "IfMemZero",
 /*  92 */ "VRowid",
 /*  93 */ "MakeRecord",
 /*  94 */ "SetCookie",
 /*  95 */ "StackDepth",
 /*  96 */ "Prev",
 /*  97 */ "ContextPush",
 /*  98 */ "DropTrigger",
 /*  99 */ "IdxGT",
 /* 100 */ "MemNull",
 /* 101 */ "IfMemNeg",
 /* 102 */ "VColumn",
 /* 103 */ "Return",
 /* 104 */ "OpenWrite",
 /* 105 */ "Integer",
 /* 106 */ "Transaction",
 /* 107 */ "CollSeq",
 /* 108 */ "Sequence",
 /* 109 */ "ContextPop",
 /* 110 */ "VCreate",
 /* 111 */ "CreateTable",
 /* 112 */ "AddImm",
 /* 113 */ "DropTable",
 /* 114 */ "IsUnique",
 /* 115 */ "VOpen",
 /* 116 */ "Noop",
 /* 117 */ "RowKey",
 /* 118 */ "Expire",
 /* 119 */ "FifoRead",
 /* 120 */ "Delete",
 /* 121 */ "IfMemPos",
 /* 122 */ "MemIncr",
 /* 123 */ "Blob",
 /* 124 */ "MakeIdxRec",
 /* 125 */ "Real",
 /* 126 */ "HexBlob",
 /* 127 */ "Goto",
 /* 128 */ "ParseSchema",
 /* 129 */ "VNext",
 /* 130 */ "Pop",
 /* 131 */ "TableLock",
 /* 132 */ "VerifyCookie",
 /* 133 */ "Column",
 /* 134 */ "OpenRead",
 /* 135 */ "ResetCount",
 /* 136 */ "NotUsed_136",
 /* 137 */ "NotUsed_137",
 /* 138 */ "ToText",
 /* 139 */ "ToBlob",
 /* 140 */ "ToNumeric",
 /* 141 */ "ToInt",
 /* 142 */ "ToReal",
};
#endif
