//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE tuiscriptadaptors
//! @file
//! @SYMTestCaseID		API-SEC-SWI-CR0914-INSTALL-B-0005
//! @SYMTestStatus		3. Released

START_TESTCASE API-SEC-SWI-CR0914-INSTALL-B-0005

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep Z:\tswi\tsisregistrytest\scripts\integritychecktest.ini SEC-SWI-CR0914-0005

END_TESTCASE API-SEC-SWI-CR0914-INSTALL-B-0005