//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run all SisRegistry tests
//
LOAD_SUITE tSisRegistryTest
LOAD_SUITE tuiscriptadaptors

//
//! @file
//! @SYMTestCaseID 		API-SEC-SWI-95817-B-0001
//! @SYMTestCaseDesc   		Check for logging filewhen Logging is off in swipolicy.ini 
//! @SYMTestExpectedResults 	Log file should not be created in private directory.

START_TESTCASE API-SEC-SWI-95817-B-0001

RUN_TEST_STEP 100 tSisRegistryTest LoggingFileInfo z:\tswi\tsisregistrytest\scripts\tsisregistrytest.ini SEC-SWI-95817-Simple-Uids

END_TESTCASE API-SEC-SWI-95817-B-0001


