//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @file
// SWIS unit (integration) tests
PRINT Run all SWIS tests
LOAD_SUITE tuiscriptadaptors
LOAD_SUITE tSisRegistryTest
LOAD_SUITE tswiconsole

//! @SYMTestCaseID 		API-SEC-LOGOTEST-0001
//! @SYMTestStatus		3. Released

START_TESTCASE API-SEC-LOGOTEST-0001
// Installation of a SIS file that contains a logo.
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuiscriptadaptors.ini logo
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuiscriptadaptors.ini u_logo

END_TESTCASE API-SEC-LOGOTEST-0001


//! @SYMTestCaseID 		API-SEC-RUNTESTMIME-0001
//! @SYMTestStatus		3. Released
//Install SIS file that runs a file by mime type will be ignored in textshell

START_TESTCASE API-SEC-RUNTESTMIME-0001	
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testrun.ini mime_textshell
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testrun.ini u_mime_textshell

END_TESTCASE API-SEC-RUNTESTMIME-0001


// Part of CR956 test 

//! @SYMTestCaseID 		API-SEC-SWI-CR956-B-0005
//! @SYMTestCaseDesc 		checks sis file with RBS  
//! @SYMREQ 			REQ7504
//! @SYMTestPriority 		Medium
//! @SYMTestActions  		Installs and uninstalls sis file with RI and RBS 
//! @SYMTestExpectedResults 	RI and RBS should be running at same time (for some duration)
//! @SYMDevelopedForRelease 	Oghma

START_TESTCASE API-SEC-SWI-CR956-B-0005
RUN_TEST_STEP_RESULT 106 tuiscriptadaptors FindRunningExe z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini infiniteexeRunning
RUN_TEST_STEP 500 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini simplerbs
DELAY 5000
RUN_TEST_STEP 100 tuiscriptadaptors FindRunningExe z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini infiniteexeRunning
CONCURRENT
RUN_TEST_STEP 500 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini u_simplerbs
RUN_TEST_STEP 100 tuiscriptadaptors FindRunningExe z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini bigexeRunning
RUN_TEST_STEP 100 tuiscriptadaptors FindRunningExe z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini infiniteexeRunning

END_TESTCASE API-SEC-SWI-CR956-B-0005


//! @SYMTestCaseID 		API-SEC-SWI-CR956-B-0009
//! @SYMTestCaseDesc 		checks sis file with RR,RI and RBS 
//! @SYMREQ 			REQ7504
//! @SYMTestPriority 		Medium
//! @SYMTestActions  		Installs and uninstalls sis file with RR, RI and RBS   
//! @SYMTestExpectedResults 	RBS should run asynchronously with RI
//! @SYMDevelopedForRelease 	Oghma

CONSECUTIVE
START_TESTCASE API-SEC-SWI-CR956-B-0009
RUN_TEST_STEP 500 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini rirbsrr
DELAY 5000
RUN_TEST_STEP 100 tuiscriptadaptors FindRunningExe z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini infiniteexeRunning
CONCURRENT
RUN_TEST_STEP 500 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini u_simplerbs
RUN_TEST_STEP 100 tuiscriptadaptors FindRunningExe z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini infiniteexeRunning
RUN_TEST_STEP 100 tuiscriptadaptors FindRunningExe z:\tswi\tuiscriptadaptors\scripts\CR956_test_armv5.ini bigexeRunning

END_TESTCASE API-SEC-SWI-CR956-B-0009

