//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run all SWIS tests
LOAD_SUITE tuiscriptadaptors

//! @SYMTestCaseID SEC-SWI-INC137499-I-0001
//! @SYMTestCaseDesc Tests for installation of sis file signed with certificate which does not have any AIA URI
//! @SYMDEF INC137499
//! @SYMTestPriority Medium
//! @SYMTestActions Tries to install the sis file successfully
//! @SYMTestExpectedResults Installation should succeed
//! @SYMDevelopedForRelease Naiad

START_TESTCASE SEC-SWI-INC137499-I-0001
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuiscriptadaptors.ini no_aia_cert
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuiscriptadaptors.ini u_no_aia_cert
END_TESTCASE SEC-SWI-INC137499-I-0001


//! @SYMTestCaseID SEC-SWI-INC137499-I-0002
//! @SYMTestCaseDesc Tests for cancellation of installation of sis file signed with certificate which does not have any AIA URI 
//! @SYMDEF INC137499
//! @SYMTestPriority Medium
//! @SYMTestActions Tries to abort the installation of the sis file after receiving a prompt
//! @SYMTestExpectedResults Installation should abort with -3
//! @SYMDevelopedForRelease Naiad

START_TESTCASE SEC-SWI-INC137499-I-0002
RUN_TEST_STEP_RESULT -3 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuiscriptadaptors.ini no_aia_cert_cancel
END_TESTCASE SEC-SWI-INC137499-I-0002