//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
// SWIS unit (integration) tests
PRINT Run all SWIS tests
LOAD_SUITE tuiscriptadaptors
LOAD_SUITE aprrtautils

// give emulator time to start up so APPARC can initialize
DELAY 5000

RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ContentOnly

//! @SYMTestCaseID		API-SEC-UISA-DRMASYNC-I-0001
//! @SYMTestCaseDesc		Install SIS files run a document asynchronously on install / uninstall with no rights
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-UISA-DRMASYNC-I-0001

RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP !Error=-17452 100 tuiscriptadaptors InstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-DRMASYNC-I-0001


//! @SYMTestCaseID		API-SEC-UISA-DRMASYNC-I-0002
//! @SYMTestCaseDesc		Install asynchronously SIS files run a document on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-UISA-DRMASYNC-I-0002

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ForwardLock
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP 100 tuiscriptadaptors InstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall
RUN_UTILS DeleteFile c:\tswi\processed.rights

END_TESTCASE API-SEC-UISA-DRMASYNC-I-0002


//! @SYMTestCaseID		API-SEC-UISA-DRMASYNC-I-0003
//! @SYMTestCaseDesc		Install SIS files run a document asynchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-UISA-DRMASYNC-I-0003

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini Pending
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP !Error=-17455 100 tuiscriptadaptors InstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall
RUN_UTILS DeleteFile c:\tswi\processed.rights

END_TESTCASE API-SEC-UISA-DRMASYNC-I-0003


//! @SYMTestCaseID		API-SEC-UISA-DRMASYNC-I-0004
//! @SYMTestCaseDesc		Install SIS files run a document asynchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-UISA-DRMASYNC-I-0004

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ExecuteDateProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP 100 tuiscriptadaptors InstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall
RUN_UTILS DeleteFile c:\tswi\processed.rights

END_TESTCASE API-SEC-UISA-DRMASYNC-I-0004


//! @SYMTestCaseID		API-SEC-UISA-DRMASYNC-I-0005
//! @SYMTestCaseDesc		Install SIS files run a document asynchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-UISA-DRMASYNC-I-0005

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ExecuteCountProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP 100 tuiscriptadaptors InstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall
RUN_UTILS DeleteFile c:\tswi\processed.rights

END_TESTCASE API-SEC-UISA-DRMASYNC-I-0005


//! @SYMTestCaseID		API-SEC-UISA-DRMASYNC-I-0006
//! @SYMTestCaseDesc		Install SIS files run a document asynchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-UISA-DRMASYNC-I-0006

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ExecuteDateExpired
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP !Error=-17451 100 tuiscriptadaptors InstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall
RUN_UTILS DeleteFile c:\tswi\processed.rights

END_TESTCASE API-SEC-UISA-DRMASYNC-I-0006


//! @SYMTestCaseID		API-SEC-UISA-DRMASYNC-I-0007
//! @SYMTestCaseDesc		Install SIS files run a document asynchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-UISA-DRMASYNC-I-0007

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ExecuteCountExpired
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP !Error=-17451 100 tuiscriptadaptors InstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall
RUN_UTILS DeleteFile c:\tswi\processed.rights

END_TESTCASE API-SEC-UISA-DRMASYNC-I-0007


//! @SYMTestCaseID		API-SEC-UISA-DRMASYNC-I-0008
//! @SYMTestCaseDesc		Install SIS files run a document asynchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-UISA-DRMASYNC-I-0008

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini DisplayCountProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP !Error=-17451 100 tuiscriptadaptors InstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallAsyncStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall
RUN_UTILS DeleteFile c:\tswi\processed.rights

END_TESTCASE API-SEC-UISA-DRMASYNC-I-0008


RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_UTILS DeleteFile c:\tswi\sis.content

// Ensure that SWIS shuts down after the above tests to make sure heap checks run
RUN_TEST_STEP 5 tuiscriptadaptors SwisNotRunning
