//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
// SWIS unit (integration) tests for upgrades
PRINT Run all SWIS tests
LOAD_SUITE tuiscriptadaptors

//! @SYMTestCaseID 		API-SEC-SWI-UISAAugmentationTest-I-0001
//! @SYMTestCaseDesc 		Test augmentationTest
//! @SYMTestPriority 		High
//! @SYMTestActions 		Perform various augmentations.
//! @SYMTestExpectedResults 	Files installed/uninstalled.
//! @SYMDevelopedForRelease 	Yankee

START_TESTCASE API-SEC-SWI-UISAAugmentationTest-I-0001

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini augmentation_base
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini u_augmentation

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini augmentation_base
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini augmentation_A
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini u_augmentation

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini augmentation_base
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini augmentation_A
RUN_TEST_STEP 100 tuiscriptadaptors UninstallAugStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini u_augmentation_A
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini u_augmentation

RUN_TEST_STEP_RESULT -10255 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini augmentation_A2
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini u_augmentation

END_TESTCASE API-SEC-SWI-UISAAugmentationTest-I-0001


// Ensure that SWIS shuts down after the above tests to make sure heap checks run
RUN_TEST_STEP 5 tuiscriptadaptors SwisNotRunning
