//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run PA and SA stub not delete tests
LOAD_SUITE tuiscriptadaptors
LOAD_SUITE tSisRegistryTest

PRINT We need DeletePreinstalledFilesOnUninstall to false for running these tests.

//! @SYMTestCaseID 		API-SEC-PANotDeleteFiles-HW-0001
//! @SYMTestCaseDesc 		Installs a PA package, Remove media card, Reinsert the card back, Files should not get deleted
//! @SYMDEF 			DEF113546
//! @SYMTestPriority 		Low
//! @SYMTestActions  		Inserts a media card which should not be cleaned up because the app is not uninstalled
//! @SYMTestExpectedResults 	Media card should not be free of installed files
//! @SYMDevelopedForRelease 	Naiad

START_TESTCASE API-SEC-PANotDeleteFiles-HW-0001

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

RUN_UTILS MKDIR e:\tswi\
RUN_UTILS MKDIR e:\tswi\preinstalled\

RUN_TEST_STEP 10 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini setup_preinstalled

RUN_TEST_STEP 100 tuiscriptadaptors InstallFHStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini install_pa

RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini u_install_pastub

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
DELAY 2000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini checkfiles_pa_notdelete

END_TESTCASE API-SEC-PANotDeleteFiles-HW-0001 



//! @SYMTestCaseID 		API-SEC-SAPropogatedNotDeleteFiles-HW-0001
//! @SYMTestCaseDesc 		Installs a SA package to a Media card, Remove the media card, Delete the Registry , Mount the card back,
//! 				Install the stub sis file, Remove the Media card, Reinsert the card back, files should not get deleted
//! @SYMDEF 			DEF113546
//! @SYMTestPriority 		Low
//! @SYMTestActions  		Inserts a media card which should not be cleaned up
//! @SYMTestExpectedResults 	Inserts a media card which should not be cleaned up
//! @SYMDevelopedForRelease 	Naiad

START_TESTCASE API-SEC-SAPropogatedNotDeleteFiles-HW-0001

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini install_sa

RUN_UTILS CopyFile e:\readme.txt c:\readme.txt
RUN_UTILS CopyFile e:\private\10202dce\8000001a_0.sis e:\8000001a_0.sis

DELAY 3000
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Cleanup previous installations
DELAY 5000
RUN_TEST_STEP 100 tSisRegistryTest DeleteRegistry
DELAY 5000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
DELAY 5000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini setup_sastub
RUN_UTILS DeleteFile c:\readme.txt

RUN_TEST_STEP 100 tuiscriptadaptors InstallFHStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini install_sastub

DELAY 2000
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini u_install_sastub

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
DELAY 2000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\teststub.ini checkfiles_sa_notdelete

//cleanup data

RUN_UTILS DeleteFile e:\readme.txt
RUN_UTILS DeleteFile e:\8000001a_0.sis
RUN_UTILS DeleteFile e:\tswi\preinstalled\preinstalledinstall.txt
RUN_UTILS DeleteFile e:\private\10202dce\8000001a_0.sis
RUN_UTILS DeleteFile e:\private\10202dce\testpreinstalled_install_dsa_l1.sis

END_TESTCASE API-SEC-SAPropogatedNotDeleteFiles-HW-0001
