//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
// SWIS unit (integration) tests
PRINT Run all SWIS tests
LOAD_SUITE tuiscriptadaptors
LOAD_SUITE aprrtautils

// give emulator time to start up so APPARC can initialize
DELAY 5000

RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ContentOnly

//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0001
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0001

RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP_RESULT -17452 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0001


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0002
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0002

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ForwardLock
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0002


//! @SYMTestCaseID 		API-SEC-UISA-RunTest-I-0003
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0003

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini Pending
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP_RESULT -17455 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0003


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0004
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0004

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ExecuteDateProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0004


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0005
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0005

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ExecuteCountProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0005


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0006
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0006

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ExecuteDateExpired
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP_RESULT -17451 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0006


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0007
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0007

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini ExecuteCountExpired
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP_RESULT -17451 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0007


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0008
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0008

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.rights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\separate_delivery.ini DisplayCountProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini Rights
RUN_TEST_STEP_RESULT -17452 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0008


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0009
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0009

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_UTILS DeleteFile c:\tswi\sis.contentrights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\combined_delivery.ini ForwardLock
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini ContentRights
RUN_TEST_STEP 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0009


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0010
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0010

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_UTILS DeleteFile c:\tswi\sis.contentrights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\combined_delivery.ini Pending
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini ContentRights
RUN_TEST_STEP_RESULT -17455 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0010


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0011
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0011

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_UTILS DeleteFile c:\tswi\sis.contentrights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\combined_delivery.ini ExecuteDateProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini ContentRights
RUN_TEST_STEP 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0011


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0012
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0012

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_UTILS DeleteFile c:\tswi\sis.contentrights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\combined_delivery.ini ExecuteCountProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini ContentRights
RUN_TEST_STEP 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0012


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0013
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0013

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_UTILS DeleteFile c:\tswi\sis.contentrights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\combined_delivery.ini ExecuteDateExpired
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini ContentRights
RUN_TEST_STEP_RESULT -17451 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0013


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0014
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0014

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_UTILS DeleteFile c:\tswi\sis.contentrights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\combined_delivery.ini ExecuteCountExpired
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini ContentRights
RUN_TEST_STEP_RESULT -17451 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0014


//! @SYMTestCaseID		API-SEC-UISA-RunTest-I-0015
//! @SYMTestCaseDesc		Install SIS files run a document synchronously on install / uninstall
//! @SYMTestPriority		Critical
//! @SYMTestActions		Files from a package are installed/uninstalled 
//! @SYMTestExpectedResults	Files are installed/uninstalled
//! @SYMDevelopedForRelease	Yankee

START_TESTCASE API-SEC-UISA-RunTest-I-0015

RUN_UTILS DeleteFile c:\sis.txt
RUN_UTILS DeleteFile c:\tswi\sis.content
RUN_UTILS DeleteFile c:\tswi\sis.contentrights
RUN_TEST_STEP 100 aprrtautils ClearRightsDb
RUN_TEST_STEP 100 aprrtautils CreateDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\combined_delivery.ini DisplayCountProtected
RUN_TEST_STEP 100 aprrtautils ImportDrmArchive z:\tswi\tuiscriptadaptors\scripts\drm\import.ini ContentRights
RUN_TEST_STEP_RESULT -17452 100 tuiscriptadaptors InstallCAFStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Install
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testdrm.ini Uninstall

END_TESTCASE API-SEC-UISA-RunTest-I-0015


// Ensure that SWIS shuts down after the above tests to make sure heap checks run
RUN_TEST_STEP 5 tuiscriptadaptors SwisNotRunning
