//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
// SWIS unit (integration) tests
PRINT Run Silent install tests
LOAD_SUITE tuiscriptadaptors


//! @SYMTestCaseID		API-SEC-SWI-CR-AWIR6FSGNJ-0001
//! @SYMTestCaseDesc		Check expected callbacks happen
//! @SYMREQ 			REQ5496 REQ5497 REQ5498
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-SWI-CR-AWIR6FSGNJ-0001

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test1_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test1_all
// Do not need to cleanup because following test formats the MMC

END_TESTCASE API-SEC-SWI-CR-AWIR6FSGNJ-0001


//! @SYMTestCaseID		API-SEC-SWI-CR-AWIR6FSGNJ-0002
//! @SYMTestCaseDesc		Tries to install a SISX file onto drive q, which is not present
//! @SYMREQ 			REQ5499
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Mike

START_TESTCASE API-SEC-SWI-CR-AWIR6FSGNJ-0002

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test2_all
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

END_TESTCASE API-SEC-SWI-CR-AWIR6FSGNJ-0002


// Copy files into place on the pre-installed drives

RUN_UTILS MKDIR c:\tswi
RUN_UTILS MKDIR c:\tswi\preinstalled
RUN_UTILS DELETEFILE k:\tswi\preinstalled\preinstalledpatch.txt
RUN_UTILS COPYFILE z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt c:\tswi\preinstalled\preinstalledinstall.txt
RUN_UTILS MAKEREADWRITE c:\tswi\preinstalled\preinstalledinstall.txt
RUN_UTILS COPYFILE z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt c:\tswi\preinstalled\preinstalledpatch.txt
RUN_UTILS MAKEREADWRITE c:\tswi\preinstalled\preinstalledpatch.txt


//Install a base package through normal installation(tuiscriptadaptors). 

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini selfsigned_base


//! @SYMTestCaseID		API-SEC-SWIDummyPlugin-I-B-0001
//! @SYMTestCaseDesc		Check expected callbacks happen when we have Base pkg and Swi-Daemon will check preinstall patch(PP) over it.
//! @SYMDEF 			DEF105776
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Naiad

START_TESTCASE API-SEC-SWIDummyPlugin-I-B-0001

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test2_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test3_all

END_TESTCASE API-SEC-SWIDummyPlugin-I-B-0001


// Install a patch over base using normal installation (tuiscriptadaptors).

// Install preinstalled patch on MMC.

RUN_UTILS COPYFILE c:\tswi\preinstalled\preinstalledpatch.txt e:\tswi\preinstalled\preinstalledpatch.txt

RUN_UTILS DELETEFILE c:\tswi\preinstalled\preinstalledpatch.txt

RUN_TEST_STEP 100 tuiscriptadaptors InstallFHStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini preinstalled_patch_e

RUN_UTILS COPYFILE z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt c:\tswi\preinstalled\preinstalledpatch.txt

//! @SYMTestCaseID		API-SEC-SWIDummyPlugin-I-B-0002
//! @SYMTestCaseDesc		Check expected callbacks happen we have Base, PP over it and Swi-Daemon will check PP again with the same name.
//! @SYMDEF 			DEF105776
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Naiad

START_TESTCASE API-SEC-SWIDummyPlugin-I-B-0002

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test2_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test4_all

END_TESTCASE API-SEC-SWIDummyPlugin-I-B-0002


//! @SYMTestCaseID		API-SEC-SWIDummyPlugin-I-B-0003
//! @SYMTestCaseDesc		Check expected callbacks happen when we have Base , PP over it and PP over it with different name using Swi-Daemon.
//! @SYMDEF 			DEF105776
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Naiad

START_TESTCASE API-SEC-SWIDummyPlugin-I-B-0003

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test3_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test5_all

END_TESTCASE API-SEC-SWIDummyPlugin-I-B-0003


RUN_UTILS MKDIR e:\tswi
RUN_UTILS MKDIR e:\tswi\preinstalled
RUN_UTILS COPYFILE c:\tswi\preinstalled\preinstalledpatch.txt e:\tswi\preinstalled\preinstalledpatch.txt
RUN_UTILS MAKEREADWRITE e:\tswi\preinstalled\preinstalledpatch.txt

// Remove base app
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini u_base


// Install base package(SA) 

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini  augmentation_base


//! @SYMTestCaseID		API-SEC-SWIDummyPlugin-I-B-0004
//! @SYMTestCaseDesc		Check expected callbacks happen when we have a Base pkg and Swi-Daemon will check SP over it.
//! @SYMDEF 			DEF105776
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Naiad

START_TESTCASE API-SEC-SWIDummyPlugin-I-B-0004

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test4_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test6_all

END_TESTCASE API-SEC-SWIDummyPlugin-I-B-0004


// Really Install the SP from normal installation. 
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini augmentation_A


//! @SYMTestCaseID		API-SEC-SWIDummyPlugin-I-B-0005
//! @SYMTestCaseDesc		Check expected callbacks happen when we have Base,SP over it and Swi-Daemon will check SP again with the same name.
//! @SYMDEF 			DEF105776
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Naiad

START_TESTCASE API-SEC-SWIDummyPlugin-I-B-0005

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test4_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test4_all

END_TESTCASE API-SEC-SWIDummyPlugin-I-B-0005


//! @SYMTestCaseID		API-SEC-SWIDummyPlugin-I-B-0006
//! @SYMTestCaseDesc		Check expected callbacks happen when we have Base,SP over it and Swi-Daemon will check SP again with different name.
//! @SYMREQ 			DEF105776
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Naiad

START_TESTCASE API-SEC-SWIDummyPlugin-I-B-0006

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test5_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test7_all

END_TESTCASE API-SEC-SWIDummyPlugin-I-B-0006


// Uninstall the augmentation and base
RUN_TEST_STEP 100 tuiscriptadaptors UninstallAugStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini u_augmentation_A
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testaugmentations.ini u_augmentation


RUN_UTILS MKDIR e:\tswi
RUN_UTILS MKDIR e:\tswi\preinstalled
RUN_UTILS COPYFILE c:\tswi\preinstalled\preinstalledpatch.txt e:\tswi\preinstalled\preinstalledinstall.txt
RUN_UTILS COPYFILE z:\tswi\tsis\data\Root5CA\dsa_len1\testpreinstalled_install_dsa_l1.sis e:\testpreinstalled_install_dsa_l1.sis


// pre-installed normal application
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini preinstalled_install


//! @SYMTestCaseID		API-SEC-SWIDummyPlugin-I-B-0007
//! @SYMTestCaseDesc		Check expected callbacks happen when we have Base pkg (PA) and Swi-Daemon will check PP over it.
//! @SYMDEF 			DEF105776
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Naiad

START_TESTCASE API-SEC-SWIDummyPlugin-I-B-0007

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test6_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test8_all

END_TESTCASE API-SEC-SWIDummyPlugin-I-B-0007


RUN_UTILS COPYFILE z:\tswi\tsis\data\Root5CA\dsa_len1\testpreinstalled_patch2_dsa_l1.sis e:\testpreinstalled_patch2_dsa_l1.sis
RUN_UTILS MAKEREADWRITE e:\testpreinstalled_patch2_dsa_l1.sis
RUN_UTILS MKDIR e:\tswi
RUN_UTILS MKDIR e:\tswi\preinstalled
RUN_UTILS COPYFILE z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt e:\tswi\preinstalled\preinstalledpatch2.txt
RUN_UTILS MAKEREADWRITE e:\tswi\preinstalled\preinstalledpatch2.txt
RUN_UTILS DELETEFILE e:\private\10202dce\81111209.sis

// pre-installed patch
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini preinstalled_patch2


//! @SYMTestCaseID		API-SEC-SWIDummyPlugin-I-B-0008
//! @SYMTestCaseDesc		Check expected callbacks happen when we have Base pkg (PA), PP over it and Swi-Daemon will check for PP again with same name.
//! @SYMDEF 			DEF105776
//! @SYMTestPriority		Medium
//! @SYMTestActions		Format MMC, copy pre-installed app to MMC, and check actions after re-inserting MMC
//! @SYMTestExpectedResults	Correct callbacks occur
//! @SYMDevelopedForRelease	Naiad

START_TESTCASE API-SEC-SWIDummyPlugin-I-B-0008

RUN_TEST_STEP_RESULT -21 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test6_h2
RUN_TEST_STEP 100 tuiscriptadaptors MmcResetTagsStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E
RUN_TEST_STEP 100 tuiscriptadaptors MmcUnMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// 1 sec delay for DP ROM performance
DELAY 1000

RUN_TEST_STEP 100 tuiscriptadaptors MmcMountStep z:\tswi\tuiscriptadaptors\scripts\drives.ini E

// Wait for the PlatSec* ERROR message, otherwise, testutilserver will get a E32User 46 error.
DELAY 7000

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tsilent.ini test4_all

END_TESTCASE API-SEC-SWIDummyPlugin-I-B-0008


RUN_UTILS MKDIR e:\tswi
RUN_UTILS MKDIR e:\tswi\preinstalled
RUN_UTILS COPYFILE c:\tswi\preinstalled\preinstalledpatch.txt e:\tswi\preinstalled\preinstalledinstall.txt
RUN_UTILS COPYFILE z:\tswi\tsis\data\Root5CA\dsa_len1\testpreinstalled_install_dsa_l1.sis e:\testpreinstalled_install_dsa_l1.sis

RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini u_preinstalled_install

RUN_UTILS MAKEREADWRITE c:\tswi\preinstalled\preinstalledpatch.txt
RUN_UTILS DELETEFILE c:\tswi\preinstalled\preinstalledpatch.txt

// End of file

// Ensure that SWIS shuts down after the above tests to make sure heap checks run
RUN_TEST_STEP 5 tuiscriptadaptors SwisNotRunning
