//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
// SWIS unit (integration) tests
PRINT Run all SWIS tests
LOAD_SUITE tuiscriptadaptors
LOAD_SUITE tbackuprestore

//! @SYMTestCaseID		API-SEC-SWI-CR1023-0001
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Uninstall th PA sis file and call ListL 
//! @SYMTestExpectedResults	ListL should list the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0001

RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini X
RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listapps
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini privatefolder

END_TESTCASE API-SEC-SWI-CR1023-0001


//! @SYMTestCaseID		API-SEC-SWI-CR1023-A-0001
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs (setting propagation to true in swiPolicy.ini) 
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis file and ctl file to relevant folders and call ListL 
//! @SYMTestExpectedResults	ListL should list the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-A-0001

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\80000001_0.sis c:\cr1023\80000001_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000001_0.sis
RUN_UTILS DeleteFile c:\cr1023\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive
RUN_UTILS DeleteFile x:\private\10202dce\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini privatefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder

END_TESTCASE API-SEC-SWI-CR1023-A-0001


//! @SYMTestCaseID		API-SEC-SWI-CR1023-B-0001
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs (setting propagation to false in swiPolicy.ini) 
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the ctl file to relevant folder and call ListL 
//! @SYMTestExpectedResults	ListL should list the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-B-0001

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder

END_TESTCASE API-SEC-SWI-CR1023-B-0001


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0002
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Uninstall the PA sis file and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should remove the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0002

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexists

END_TESTCASE API-SEC-SWI-CR1023-0002


//! @SYMTestCaseID		API-SEC-SWI-CR1023-A-0002
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis file and ctl file to relevant folders and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should remove the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-A-0002

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\80000001_0.sis c:\cr1023\80000001_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000001_0.sis
RUN_UTILS DeleteFile c:\cr1023\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeappsxdrive
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexistssisctl
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder

END_TESTCASE API-SEC-SWI-CR1023-A-0002


//! @SYMTestCaseID		API-SEC-SWI-CR1023-B-0002
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the ctl file to relevant folders and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should remove the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-B-0002

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeappsxdrive
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexists
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder

END_TESTCASE API-SEC-SWI-CR1023-B-0002


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0003
//! @SYMTestCaseDesc		Retrieving Package details of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7565
//! @SYMTestPriority		Medium
//! @SYMTestActions		Uninstall the PA sis file and call API's to get package details 
//! @SYMTestExpectedResults	Details of uninstalled pkg should be retrieved
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0003

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP 100 tuiscriptadaptors GetPackageDetails z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini  getpkgdetails
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini privatefolder

END_TESTCASE API-SEC-SWI-CR1023-0003


//! @SYMTestCaseID		API-SEC-SWI-CR1023-A-0003
//! @SYMTestCaseDesc		Retrieving Package details of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7565
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis file and ctl file to relevant folders and call API's to get the package details 
//! @SYMTestExpectedResults	Details of uninstalled pkg should be retrieved
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-A-0003

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\80000001_0.sis c:\cr1023\80000001_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000001_0.sis
RUN_UTILS DeleteFile c:\cr1023\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_TEST_STEP 100 tuiscriptadaptors GetPackageDetails z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini getpkgdetails_stubsis
RUN_UTILS DeleteFile x:\private\10202dce\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini privatefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder

END_TESTCASE API-SEC-SWI-CR1023-A-0003


//! @SYMTestCaseID		API-SEC-SWI-CR1023-B-0003
//! @SYMTestCaseDesc		Retrieving Package details of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7565
//! @SYMTestPriority		Medium
//! @SYMTestActions		 Copy the ctl file to relevant folders and call API's to get the package details
//! @SYMTestExpectedResults	Details of uninstalled pkg should be retrieved
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-B-0003

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple
// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl
// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\testpreinstalled.ini u_simple
// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_TEST_STEP 100 tuiscriptadaptors GetPackageDetails z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini getpkgdetails_stubsis
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder

END_TESTCASE API-SEC-SWI-CR1023-B-0003

   
//! @SYMTestCaseID		API-SEC-SWI-CR1023-0004
//! @SYMTestCaseDesc		Read capability check for ListL and packageDetails information 
//! @SYMREQ			REQ7570
//! @SYMTestPriority		Medium
//! @SYMTestActions		Execute the exe's with and without readdevicedata capabilities and call the ListL 
//! @SYMTestExpectedResults	The exe with capability should retrieve the information and one without should not
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0004

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_PROGRAM  testappwithoutrc.exe 
RUN_PROGRAM testappwithrc.exe
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x.sis

END_TESTCASE API-SEC-SWI-CR1023-0004


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0005
//! @SYMTestCaseDesc		Write capability check for RemoveL 
//! @SYMREQ			REQ7570
//! @SYMTestPriority		Medium
//! @SYMTestActions		Execute the exe's with and without writedevicedata capabilities and call the RemoveL 
//! @SYMTestExpectedResults	The exe with capability should remove the uninstalled package and one without should not
//! @SYMDevelopedForRelease	Oghma
   
START_TESTCASE API-SEC-SWI-CR1023-0005

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_PROGRAM  testappwithoutwc.exe 
RUN_PROGRAM testappwithwc.exe
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexists

END_TESTCASE API-SEC-SWI-CR1023-0005


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0010
//! @SYMTestCaseDesc		Directory removal check for RemoveL 
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether empty directoy is removed 
//! @SYMTestExpectedResults	The empty directory should be removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0010

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_UTILS MKDIR x:\tswi\
RUN_UTILS MKDIR x:\tswi\preinstalled\
RUN_UTILS CopyFile  z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt  x:\tswi\preinstalled\preinstalledinstall_x.txt
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexists
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexistsdir

END_TESTCASE API-SEC-SWI-CR1023-0010


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0011
//! @SYMTestCaseDesc		Directory removal check for RemoveL 
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether non-empty directoy is not removed 
//! @SYMTestExpectedResults	The non-empty directory should not be removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0011

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_UTILS MKDIR x:\tswi\
RUN_UTILS MKDIR x:\tswi\preinstalled\
RUN_UTILS CopyFile  z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt  x:\tswi\preinstalled\preinstalledinstall_x.txt
RUN_UTILS CopyFile  z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt  x:\tswi\preinstalled\preinstalledinstall_x_1.txt
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexists
RUN_TEST_STEP  !Result=Fail 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexistsdir
RUN_UTILS DeleteDirectory  x:\tswi

END_TESTCASE API-SEC-SWI-CR1023-0011


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0012
//! @SYMTestCaseDesc		File removal check for RemoveL for FN
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether files referred using FN is removed 
//! @SYMTestExpectedResults	The file should be removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0012

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_filenull.sis x:\private\10202dce\testpreinstalled_install_filenull.sis
RUN_UTILS MKDIR x:\Documents\
RUN_UTILS MKDIR x:\Documents\InstTest\
RUN_UTILS CopyFile z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt x:\Documents\InstTest\file1.txt
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini filenullchk

END_TESTCASE API-SEC-SWI-CR1023-0012


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0013
//! @SYMTestCaseDesc		File removal check for RemoveL for not orphaned FN
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether files referred using FN is not removed if it is not orphaned
//! @SYMTestExpectedResults	The file should not be removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0013

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_filenull.sis x:\private\10202dce\testpreinstalled_install_filenull.sis
RUN_UTILS MKDIR x:\tswi\
RUN_UTILS MKDIR x:\tswi\preinstalled\
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeselectedfilenullpkg
RUN_TEST_STEP !Result=fail 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini filenotorphaned

RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple
RUN_UTILS DeleteDirectory   x:\tswi
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini privatefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0013


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0014
//! @SYMTestCaseDesc		File removal check for RemoveL for FN where the file is in data caged area
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether files referred using FN which are in data caged area is not removed
//! @SYMTestExpectedResults	The file should not be removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0014

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_datacaged_filenull.sis x:\private\10202dce\testpreinstalled_datacaged_filenull.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copydatacagedfilenull
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps
RUN_TEST_STEP !Result=fail 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini datacagedfilenull
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0014


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0008
//! @SYMTestCaseDesc		File removal check for RemoveL for not orphaned file
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether files referred is not removed if it is not orphaned
//! @SYMTestExpectedResults	The file should not be removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0008

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x2.sis x:\private\10202dce\testpreinstalled_install_x2.sis
RUN_UTILS MKDIR x:\tswi\
RUN_UTILS MKDIR x:\tswi\preinstalled\
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeselectedpkg
RUN_TEST_STEP !Result=fail 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini filenotorphaned

RUN_UTILS DeleteDirectory   x:\tswi
RUN_UTILS DeleteDirectory   x:\private
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0008


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0007
//! @SYMTestCaseDesc		File removal check for RemoveL for data caged file
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether files referred is removed if it is data caged
//! @SYMTestExpectedResults	The file is removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0007

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x3.sis x:\private\10202dce\testpreinstalled_install_x3.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copydatacagedfile
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini datacagedfile

END_TESTCASE API-SEC-SWI-CR1023-0007


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0006
//! @SYMTestCaseDesc		Exclusive RemoveL check
//! @SYMREQ			REQ7566
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and simultaneously install a sis file
//! @SYMTestExpectedResults	The installation should fail
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0006

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\80000001_0.sis c:\cr1023\80000001_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000001_0.sis
RUN_UTILS DeleteFile c:\cr1023\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x2.sis x:\private\10202dce\testpreinstalled_install_x2.sisx
CONCURRENT
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeallappsfromxdrive
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple_concurrent
CONSECUTIVE
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple1_sis
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x.sis
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x2.sisx
RUN_UTILS DeleteFile x:\private\10202dce\80000001_0.sis

END_TESTCASE API-SEC-SWI-CR1023-0006


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0015
//! @SYMTestCaseDesc		ListL check for invalid ctl file
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Move an invalid ctl file and call ListL
//! @SYMTestExpectedResults	The List should not list the ctl file
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0015

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctlinvalidfolder
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini deletectlinvalidfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0015


//! @SYMTestCaseID		API-SEC-SWI-CR1023-A-0015
//! @SYMTestCaseDesc		ListL check for invalid ctl file
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Move an invalid ctl file and call ListL
//! @SYMTestExpectedResults	The List should not list the ctl file
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-A-0015

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctlinvalidfolder1
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini deletectlinvalidfolder1
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-A-0015


//! @SYMTestCaseID		API-SEC-SWI-CR1023-B-0015
//! @SYMTestCaseDesc		ListL check for invalid ctl file
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Move an invalid ctl file and call ListL
//! @SYMTestExpectedResults	The List should not list the ctl file
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-B-0015

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctlinvalidfolder2
RUN_TEST_STEP !Error=-10283 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini deletectlinvalidfolder2
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-B-0015


//! @SYMTestCaseID		API-SEC-SWI-CR1023-C-0015
//! @SYMTestCaseDesc		ListL check for invalid ctl file
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Move an invalid ctl file and call ListL
//! @SYMTestExpectedResults	The List should not list the ctl file
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-C-0015

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctlinvalidfolder6dig
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini deletectlinvalidfolder6dig
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-C-0015


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0016
//! @SYMTestCaseDesc		ListL check for invalid sis file
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Move an invalid sis file and call ListL
//! @SYMTestExpectedResults	The List should not list the sis file
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0016

// Copy the invalid stub into position on the x: drive
//The list should not list the file
RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt x:\private\10202dce\80000001.sis
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0
RUN_UTILS DeleteDirectory  x:\private

END_TESTCASE API-SEC-SWI-CR1023-0016


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0017
//! @SYMTestCaseDesc		ListL check for invalid ctl file
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Move a valid ctl file and an invalid ctl file and call ListL
//! @SYMTestExpectedResults	The List should list only the ctl file
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0017

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctlinvalidfolder3
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini deletectlinvalidfolder3
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0017


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0018
//! @SYMTestCaseDesc		ListL should list only uninstalled pkg file
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Install a sis file and call ListL
//! @SYMTestExpectedResults	The List should not list the installed sis file
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0018

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listapps
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple
RUN_UTILS DeleteDirectory x:\private
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0018


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0019
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs when stub sis is present in removable drive
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		call ListL 
//! @SYMTestExpectedResults	ListL should return with count of zero packages for non-removable drive
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0019

RUN_UTILS MKDIR c:\private\
RUN_UTILS MKDIR c:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install.sis c:\private\10202dce\testpreinstalled_install.sis
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0
RUN_UTILS DeleteDirectry c:\private

END_TESTCASE API-SEC-SWI-CR1023-0019


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0020
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs when none is present
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		call ListL 
//! @SYMTestExpectedResults	ListL should return with count of zero packages
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0020

RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0

END_TESTCASE API-SEC-SWI-CR1023-0020


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0022
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs from non-removable drive 
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis file to relevant folders of non-removable drive and call ListL 
//! @SYMTestExpectedResults	ListL should return with KErrNotRemovable
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0022

RUN_UTILS MKDIR c:\private\
RUN_UTILS MKDIR c:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install.sis c:\private\10202dce\testpreinstalled_install.sis
RUN_TEST_STEP !Error=-10280 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappscdrive
RUN_UTILS DeleteFile c:\private\10202dce\testpreinstalled_install.sis

END_TESTCASE API-SEC-SWI-CR1023-0022


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0024
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs , with file referred as $(system drive) in pkg file
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis file and ctl file to relevant folders and call ListL 
//! @SYMTestExpectedResults	RemoveL should not remove the file from system drive
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0024

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_sysdrive.sis x:\private\10202dce\testpreinstalled_sysdrive.sis
RUN_UTILS MKDIR c:\Documents\
RUN_UTILS MKDIR c:\Documents\InstTest\
RUN_UTILS CopyFile z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt c:\Documents\InstTest\file1.txt
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps
RUN_TEST_STEP !Result=Fail 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini filesysdrivechk
RUN_UTILS DeleteDirectory c:\Documents

END_TESTCASE API-SEC-SWI-CR1023-0024


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0025
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs when only sys\install\sisregistry is present
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		call ListL 
//! @SYMTestExpectedResults	ListL should return with count of zero packages
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0025

RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyfiletosisregistry
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini deletefilefromsisregistry
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyfiletosisregistryfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini deletefilefromsisregistryfolder
RUN_TEST_STEP 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsxdrive_0
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0025


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0026
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs  with PU pkg
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Uninstall the PA sis file and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should remove the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0026

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\fileeclipsepu.sis x:\private\10202dce\fileeclipsepu.sis
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexistspusis

END_TESTCASE API-SEC-SWI-CR1023-0026


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0027
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs, when junk file is present in sys/install/sisregistry with 8 chars
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis file and ctl file to relevant folders and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should remove the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0027

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\80000001_0.sis c:\cr1023\80000001_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000001_0.sis
RUN_UTILS DeleteFile c:\cr1023\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyjunkfile
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeappsxdrive
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexistssisctl
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini deletejunkfile
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0027


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0028
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs, when same stub sis file is copied twice
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis file(twice) and ctl file to relevant folders and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should remove the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0028

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\80000001_0.sis c:\cr1023\80000001_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000001_0.sis
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000002_0.sis
RUN_UTILS DeleteFile c:\cr1023\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeappsxdrive
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeappsxdrive
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexistssisctl
RUN_UTILS DeleteDirectiry x:\private
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0028


//! @SYMTestCaseID		API-SEC-SWI-CR1023-B-0026
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs , with SA and SP
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis files and call RemoveL
//! @SYMTestExpectedResults	RemoveL should remove both the files
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-B-0026

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testaugmentations_base.sis x:\private\10202dce\testaugmentations_base.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\testaugmentations_A.sis x:\private\10202dce\testaugmentations_A.sis
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps2
RUN_UTILS RemoveDirectory x:\private

END_TESTCASE API-SEC-SWI-CR1023-B-0026


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0029
//! @SYMTestCaseDesc		check for pkg with PA and PP
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether files referred is removed
//! @SYMTestExpectedResults	The file should be removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0029

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x3.sis x:\private\10202dce\testpreinstalled_install_x3pa.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x3pp.sis x:\private\10202dce\testpreinstalled_install_x3pp.sis
RUN_UTILS MKDIR x:\Documents\
RUN_UTILS MKDIR x:\Documents\InstTest\
RUN_UTILS CopyFile z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt x:\Documents\InstTest\file1.txt
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps2
RUN_UTILS DeleteDirectory   x:\Documents

END_TESTCASE API-SEC-SWI-CR1023-0029


//! @SYMTestCaseID		API-SEC-SWI-CR1023-B-0006
//! @SYMTestCaseDesc		Exclusive RemoveL check
//! @SYMREQ			REQ7566
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and simultaneously uninstall a sis file
//! @SYMTestExpectedResults	The installation should fail
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-B-0006

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\80000001_0.sis c:\cr1023\80000001_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000001_0.sis
RUN_UTILS DeleteFile c:\cr1023\80000001_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x3.sis x:\private\10202dce\testpreinstalled_install_x3.sis
RUN_TEST_STEP 100 tbackuprestore INSTALL z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini backupandrestore
RUN_TEST_STEP 100 tbackuprestore PRESENT z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini backupandrestore
RUN_TEST_STEP 100 tbackuprestore BACKUP	z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini backupandrestore
RUN_TEST_STEP 100 tbackuprestore UNINSTALL z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini backupandrestore
CONCURRENT
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeallappsfromx
RUN_TEST_STEP 100 tbackuprestore RESTORE z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini backupandrestore

CONSECUTIVE
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tbackuprestore UNINSTALL z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini backupandrestore
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x.sis
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x3.sis
RUN_UTILS DeleteFile x:\private\10202dce\80000001_0.sis

END_TESTCASE API-SEC-SWI-CR1023-B-0006


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0030
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs after delete
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Uninstall the PA sis file, delete the file after ListL and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should return with count of 0 
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0030

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP_RESULT -1 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeappsafterdelete
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexists
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini privatefolder

END_TESTCASE API-SEC-SWI-CR1023-0030


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0031
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs for embedded files 
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the ctl file to relevant folders and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should remove the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0031

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini embedc1install
RUN_UTILS CopyFile z:\tswi\tsis\data\053177c_2.sis x:\private\10202dce\053177c_2.sis
RUN_UTILS CopyFile z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt x:\Documents\def053177\backlight.txt
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeembedapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexistsembed
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_embedc1install
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder

END_TESTCASE API-SEC-SWI-CR1023-0031


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0032
//! @SYMTestCaseDesc		Removing of Uninstalled Preinstalled Pkgs for embedded files
//! @SYMREQ			REQ7564
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the ctl file to relevant folders and call RemoveL 
//! @SYMTestExpectedResults	RemoveL should remove the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0032

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini embedc1install
RUN_UTILS CopyFile z:\tswi\tsis\data\053177c_2.sis x:\private\10202dce\053177c_2.sis
RUN_UTILS CopyFile z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt x:\Documents\def053177\backlight.txt
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\Documents\def053177\appcap1.txt c:\cr1023\appcap1.txt
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_embedc1installc0
RUN_UTILS CopyFile c:\cr1023\appcap1.txt x:\Documents\def053177\appcap1.txt
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeembedapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini notexistsembedtxt
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_embedc1installc1
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder

END_TESTCASE API-SEC-SWI-CR1023-0032


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0033
//! @SYMTestCaseDesc		check for pkg with more than 1 lang
//! @SYMREQ			REQ7567
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and check whether files referred is removed
//! @SYMTestExpectedResults	The file should be removed
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0033

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\language_frfirst.sis x:\private\10202dce\language_frfirst.sis
RUN_UTILS MKDIR x:\Documents\
RUN_UTILS MKDIR x:\Documents\InstTest\
RUN_UTILS CopyFile z:\tswi\tuiscriptadaptors\data\preinstalledinstall.txt x:\Documents\InstTest\file1.txt
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeappsxdrive
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini filelangsis
RUN_UTILS DeleteDirectory   x:\Documents

END_TESTCASE API-SEC-SWI-CR1023-0033


//! @SYMTestCaseID		API-SEC-SWI-CR1023-C-0006
//! @SYMTestCaseDesc		Exclusive RemoveL check
//! @SYMREQ			REQ7566
//! @SYMTestPriority		Medium
//! @SYMTestActions		Call the removeL and simultaneously restore a sis file
//! @SYMTestExpectedResults	The installation should fail
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-C-0006

RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple

// Copy the stub that was created and the file1.txt installed by SIMPLE.SIS
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\80000001_0.sis c:\cr1023\80000001_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\80000001\00000000_0000.ctl c:\cr1023\00000000_0000.ctl

// Uninstall SIMPLE.SIS
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\80000001_0.sis x:\private\10202dce\80000001_0.sis
RUN_UTILS DeleteFile c:\cr1023\80000001.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copyctl
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_UTILS CopyFile z:\tswi\tsis\data\testpreinstalled_install_x.sis x:\private\10202dce\testpreinstalled_install_x.sis
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini simple1_sis
CONCURRENT
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple1_sis
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeappsfromxdrive
CONSECUTIVE
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini cdrivefolder
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini sisfolder
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_simple1_sis
RUN_UTILS DeleteFile x:\private\10202dce\80000001_0.sis
RUN_UTILS DeleteFile x:\private\10202dce\testpreinstalled_install_x.sis

END_TESTCASE API-SEC-SWI-CR1023-C-0006


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0034
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs when none is present( after partial formating)
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		call ListL 
//! @SYMTestExpectedResults	ListL should return with KErrNoUninstalledPackages
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0034

RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini XFAT
RUN_TEST_STEP !Result=Fail 100 tuiscriptadaptors ListUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listapps
RUN_TEST_STEP 100 tuiscriptadaptors MmcFormatStep z:\tswi\tuiscriptadaptors\scripts\drives.ini X

END_TESTCASE API-SEC-SWI-CR1023-0034


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0035
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		uninstall the deepembed sis file and call listL
//! @SYMTestExpectedResults	ListL should list the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0035

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\053177c_8.sis x:\private\10202dce\053177c_8.sis
RUN_TEST_STEP_RESULT -10283 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsdeepembed
RUN_UTILS DeleteFile x:\private\10202dce\053177c_8.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcDeleteFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini privatefolder

END_TESTCASE API-SEC-SWI-CR1023-0035


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0036
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs  
//! @SYMREQ			REQ7561
//! @SYMTestPriority		Medium
//! @SYMTestActions		uninstall the deepembed sis file and call listL
//! @SYMTestExpectedResults	ListL should list the uninstalled pkg
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0036

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\053177c_1.sis x:\private\10202dce\053177c_1.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177c_2.sis x:\private\10202dce\053177c_2.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177c_3.sis x:\private\10202dce\053177c_3.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177c_4.sis x:\private\10202dce\053177c_4.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177b_0.sis x:\private\10202dce\053177b_0.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177b_1.sis x:\private\10202dce\053177b_1.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177b_2.sis x:\private\10202dce\053177b_2.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177b_3.sis x:\private\10202dce\053177b_3.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177b_4.sis x:\private\10202dce\053177b_4.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177b_5.sis x:\private\10202dce\053177b_5.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\053177b_6.sis x:\private\10202dce\053177b_6.sis

RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini listappsmorepkgs

END_TESTCASE API-SEC-SWI-CR1023-0036


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0037
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs , with SA and two SP
//! @SYMDEF			DEF110017
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis files and call RemoveL
//! @SYMTestExpectedResults	RemoveL should remove all 3 files.
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0037

RUN_UTILS MKDIR x:\private\
RUN_UTILS MKDIR x:\private\10202dce\
RUN_UTILS CopyFile z:\tswi\tsis\data\testaugmentations_base.sis x:\private\10202dce\testaugmentations_base.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\testaugmentations_A.sis x:\private\10202dce\testaugmentations_A.sis
RUN_UTILS CopyFile z:\tswi\tsis\data\testaugmentations_D.sis x:\private\10202dce\testaugmentations_D.sis
RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps3
RUN_UTILS RemoveDirectory x:\private

END_TESTCASE API-SEC-SWI-CR1023-0037


//! @SYMTestCaseID		API-SEC-SWI-CR1023-0038
//! @SYMTestCaseDesc		Listing of Uninstalled Preinstalled Pkgs , with SA and two SP with both controller and stub sis file
//! @SYMDEF			DEF110017
//! @SYMTestPriority		Medium
//! @SYMTestActions		Copy the stub sis files and the controller files and  call RemoveL
//! @SYMTestExpectedResults	RemoveL should remove all the files
//! @SYMDevelopedForRelease	Oghma

START_TESTCASE API-SEC-SWI-CR1023-0038

// Install augmentaion base, A and D
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini augmentation_base_x
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini augmentation_A_x
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini augmentation_D_x

// Copy the stub that was created and the controller
RUN_UTILS MKDIR c:\cr1023\
RUN_UTILS CopyFile x:\private\10202dce\81111207_0.sis c:\cr1023\81111207_0.sis
RUN_UTILS CopyFile x:\sys\install\sisregistry\81111207\00000000_0000.ctl c:\cr1023\00000000_0000.ctl
RUN_UTILS CopyFile x:\sys\install\sisregistry\81111207\00000001_0000.ctl c:\cr1023\00000001_0000.ctl
RUN_UTILS CopyFile x:\sys\install\sisregistry\81111207\00000002_0000.ctl c:\cr1023\00000002_0000.ctl

// Uninstall augmentaion base, A and D
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini u_augmentation_base_x

// Copy the stub back into position on the x: drive
// Copy the controller file to x: drive
//The list should list the file

RUN_UTILS MkDir x:\private\
RUN_UTILS MkDir x:\private\10202dce\
RUN_UTILS CopyFile c:\cr1023\81111207_0.sis x:\private\10202dce\81111207_0.sis
RUN_UTILS DeleteFile c:\cr1023\81111207_0.sis
RUN_TEST_STEP 100 tuiscriptadaptors MmcCopyFilesStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini copy3ctl
RUN_UTILS DeleteFile c:\cr1023\00000000_0000.ctl
RUN_UTILS DeleteFile c:\cr1023\00000001_0000.ctl
RUN_UTILS DeleteFile c:\cr1023\00000002_0000.ctl

RUN_TEST_STEP 100 tuiscriptadaptors RemoveUninstallPkgsStep z:\tswi\tuiscriptadaptors\scripts\tuninstallpkgs.ini removeapps3
RUN_UTILS RemoveDirectory x:\private

END_TESTCASE API-SEC-SWI-CR1023-0038

