// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Device supported language tests

// Load Suite
LOAD_SUITE tscr -SharedData
SHARED_DATA z:\tusif\tscr\tscr.ini shared_data
LOAD_SUITE tSisRegistryTest
LOAD_SUITE tscrapparc


//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		API-INST-testcase-InterpretSIS-09
//! @SYMTestCaseDesc 		Testcase to test appproperty string value
//! @SYMPREQ  			PREQ1835
//! @SYMTestStatus		Released
//! @SYMTestPriority 		High
//! @SYMTestActions 		Testcase to test appproperty string value
//! @SYMTestExpectedResults 	string value should be same as mentioned in ini file
//! @SYMTestType		CIT
//////////////////////////////////////////////////////////////////////////////////////////////



START_TESTCASE API-INST-testcase-InterpretSIS-09

RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_english
RUN_TEST_STEP 100 tscrapparc ScrGetApplicationRegistrationView c:\tswi\tinterpretsisinteg\scripts\ini.ini ApplicationRegistrationData_appproperty

END_TESTCASE API-INST-testcase-InterpretSIS-09


