// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Device supported language tests

// Load Suite
LOAD_SUITE tscr -SharedData
SHARED_DATA z:\tusif\tscr\tscr.ini shared_data
LOAD_SUITE tSisRegistryTest
LOAD_SUITE tscrapparc


//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		API-INST-testcase-InterpretSIS-01
//! @SYMTestCaseDesc 		Verify SCR for All positive scenario.
//! @SYMPREQ  			PREQ1835
//! @SYMTestStatus		Released
//! @SYMTestPriority 		High
//! @SYMTestActions 		Check SCR for All positive scenario.
//! @SYMTestExpectedResults 	ViewData should be shown in current running language.
//! @SYMTestType		CIT
//////////////////////////////////////////////////////////////////////////////////////////////



START_TESTCASE API-INST-testcase-InterpretSIS-01

// Delete the SCR Database file
//RUN_TEST_STEP 100 tscr SCRDeleteDbFile c:\tswi\tinterpretsisinteg\scripts\ini.ini db_file 

RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_english
//Test for ViewInfo, Locale = Eng
RUN_TEST_STEP 100 tscr ScrGetAppViewInfo c:\tswi\tinterpretsisinteg\scripts\ini.ini get_app_view_info_partial_eng
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_german
//Test for ViewInfo, Locale = German
RUN_TEST_STEP 100 tscr ScrGetAppViewInfo c:\tswi\tinterpretsisinteg\scripts\ini.ini get_app_view_info_partial_ger
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_spanish
//Test for AppOwnedFiles, Locale = Spanish
RUN_TEST_STEP 100 tscr SCRGetAppOwnedFilesEntry c:\tswi\tinterpretsisinteg\scripts\ini.ini appownedfiles_spn
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_english
RUN_TEST_STEP 100 tscrapparc ScrGetApplicationRegistrationView c:\tswi\tinterpretsisinteg\scripts\ini.ini ApplicationRegistrationData_MultipleApp_Locale_Eng
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_german
RUN_TEST_STEP 100 tscrapparc ScrGetApplicationRegistrationView c:\tswi\tinterpretsisinteg\scripts\ini.ini ApplicationRegistrationData_MultipleApp_Locale_Ger
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_spanish
RUN_TEST_STEP 100 tscrapparc ScrGetApplicationRegistrationView c:\tswi\tinterpretsisinteg\scripts\ini.ini ApplicationRegistrationData_MultipleApp_Locale_Spn
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_french
//Test for nearest language locale
RUN_TEST_STEP 100 tscrapparc ScrGetApplicationRegistrationView c:\tswi\tinterpretsisinteg\scripts\ini.ini ApplicationRegistrationData_MultipleApp_Locale_Frn
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_english

END_TESTCASE API-INST-testcase-InterpretSIS-01


