//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

PRINT Device supported language tests

LOAD_SUITE tuiscriptadaptors
LOAD_SUITE tSisRegistryTest



//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		API-INST-PREQ2525-InterpretSIS-18
//! @SYMTestCaseDesc 		Verify new registry version for Equivalent languages 
//! @SYMPREQ  			PREQ2525
//! @SYMTestStatus		Released
//! @SYMTestPriority 		High
//! @SYMTestActions 		Check localized package name.
//! @SYMTestExpectedResults 	Localized package name should be shown in current running language or in equivalent of current running language.
//! @SYMTestType		CIT
//////////////////////////////////////////////////////////////////////////////////////////////



START_TESTCASE API-INST-PREQ2525-InterpretSIS-18
// Check localized package name for SA and PU
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_french
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_package_info_swiss_belgian_french
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini  langauge_to_german
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_package_info_swiss_german
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_american_english
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_package_info_english_am
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_english
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_package_info_english_en
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_french
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_sp_package_info_swiss_belgian_french
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini  langauge_to_german
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_sp_package_info_swiss_german
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_american_english
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_sp_package_info_english_am
// Check localized package name for SP
RUN_TEST_STEP 100 tuiscriptadaptors UninstallAugStep c:\tswi\tinterpretsisinteg\scripts\ini.ini uninstall_sp_bf_sg_sr_sa_options
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_french
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_package_info_swiss_belgian_french
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini  langauge_to_german
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_package_info_swiss_german
RUN_TEST_STEP 100 tSisRegistryTest ChangeLocale c:\tswi\tinterpretsisinteg\scripts\ini.ini langauge_to_american_english
RUN_TEST_STEP 100 tSisRegistryTest IsPackageInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini equ_package_info_english_am
RUN_TEST_STEP 100 tuiscriptadaptors UninstallAsyncStep c:\tswi\tinterpretsisinteg\scripts\ini.ini uninstall_base_bf_sg_sr_sa_options


END_TESTCASE API-INST-PREQ2525-InterpretSIS-18


