// Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/sfl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//

// Load Suite
LOAD_SUITE tuiscriptadaptors

//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		INT-RomInstall-09
//! @SYMTestCaseDesc 	Installing SA on Rom Stub. This is a positive testcase 
//! @SYMPREQ  			
//! @SYMTestStatus		Released
//! @SYMTestPriority 	High
//! @SYMTestActions 	Install SIS file
//! @SYMTestExpectedResults 	error code 0 returned.
//! @SYMTestType		CIT
//////////////////////////////////////////////////////////////////////////////////////////////
RUN_UTILS DeleteDirectory c:\sys\bin
RUN_UTILS DeleteDirectory c:\sys\hash
RUN_UTILS DeleteDirectory c:\sys\install
RUN_UTILS DeleteDirectory c:\Documents

START_TESTCASE INT-RomInstall-09

RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep c:\tswi\tinterpretsisinteg\scripts\ini.ini ROM-Install-09_checkfiles
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini ROM-Install-09
RUN_TEST_STEP 100 tuiscriptadaptors MmcCheckFilesStep c:\tswi\tinterpretsisinteg\scripts\ini.ini ROM-Install-09_checkfilesall
//RUN_TEST_STEP_RESULT -5 100 tuiscriptadaptors UninstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini  NR-OPTION-01

END_TESTCASE INT-RomInstall-09