//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
// @file swi001-002.script
// 
//

LOAD_SUITE tuiscriptadaptors
LOAD_SUITE tSisRegistryTest

//! @SYMTestCaseID 		API-SEC-sistools-InterpretSIS-SWI001-0002
//! @SYMTestCaseDesc 		Compare installation of SWI and Interpretsis 
//! @SYMPREQ  			PREQ2114
//! @SYMTestStatus		3. Released
//! @SYMTestPriority 		High
//! @SYMTestActions 		1. Check to see if the SA + RU + NR installed successfully
//!				2. Install a SP
//!				3. Install a PU
//!				4. Uninstall the SA + RU + NR
//! @SYMTestExpectedResults 	SP installs successfully, PU upgrade fails to install and the SA + RU + NR PKG can not be uninstalled   
//! @SYMTestType		CIT

START_TESTCASE API-SEC-sistools-InterpretSIS-SWI001-0002

RUN_TEST_STEP 100 tSisRegistryTest IsUidInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini 001-002_SA_RU_NR
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini 001-001_SP
RUN_TEST_STEP_RESULT -10256 100 tuiscriptadaptors InstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini 001-001_PU
RUN_TEST_STEP_RESULT -5 100 tuiscriptadaptors UninstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini  u_001-002_SA_RU_NR
RUN_TEST_STEP 100 tuiscriptadaptors ForceRemove c:\tswi\tinterpretsisinteg\scripts\ini.ini 811111FD_files

END_TESTCASE API-SEC-sistools-InterpretSIS-SWI001-0002
