//
// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
// @file swi001-007.script
// interpretsis Integration Test Script
// Integration Test
// Component  : SWI
// Tests      : 
// The scope of this script is to compare the SWI and Interpretsis installation
//


PRINT Run test for installation of sis file 
LOAD_SUITE tuiscriptadaptors
LOAD_SUITE tSisRegistryTest

//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		API-SEC-sistools-InterpretSIS-SWI001-0007
//! @SYMTestCaseDesc 		Compare installation of SWI and Interpretsis Adorned file name eclipsing
//! @SYMPREQ  			PREQ2114
//! @SYMTestStatus		3. Released
//! @SYMTestPriority 		High
//! @SYMTestActions 		Install a SP with installing file A.dll over the existing SA package 
//!				with adorned file A{000A0001}.dll installations
//! @SYMTestExpectedResults 	Installation should pass     
//! @SYMTestType		CIT
//////////////////////////////////////////////////////////////////////////////////////////////
START_TESTCASE API-SEC-sistools-InterpretSIS-SWI001-0007

RUN_TEST_STEP 100 tSisRegistryTest IsUidInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini SWI001-007_SA
RUN_TEST_STEP 100 tuiscriptadaptors InstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini SWI001-007_SP
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini uSWI001-007

END_TESTCASE API-SEC-sistools-InterpretSIS-SWI001-0007


