//
// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
// @file tintsis.script
// interpretsis Integration Test Script
// Integration Test
// Component  : SWI
// Tests      : 
// The scope of this script is to compare the SWI and Interpretsis installation
//


PRINT Run test for installation of sis file 
LOAD_SUITE tuiscriptadaptors
LOAD_SUITE tSisRegistryTest

//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		API-SEC-sistools-InterpretSIS-SWI001-0006
//! @SYMTestCaseDesc 		Compare installation of SWI and Interpretsis 
//! @SYMPREQ  			PREQ2114
//! @SYMTestStatus		3. Released
//! @SYMTestPriority 		High
//! @SYMTestActions 		Install a PU over the existing Stub->SA installations
//! @SYMTestExpectedResults 	Installation failed as the PU delivers a different file name with the same SID     
//! @SYMTestType		CIT
//////////////////////////////////////////////////////////////////////////////////////////////
RUN_UTILS DeleteDirectory c:\sys\bin
RUN_UTILS DeleteDirectory c:\sys\hash
RUN_UTILS DeleteDirectory c:\sys\install

START_TESTCASE API-SEC-sistools-InterpretSIS-SWI001-0006

RUN_TEST_STEP 100 tSisRegistryTest IsUidInstalled c:\tswi\tinterpretsisinteg\scripts\ini.ini SWI001-006_SA_RU_NR
RUN_TEST_STEP_RESULT -11 100 tuiscriptadaptors InstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini SWI001-006_PU
RUN_TEST_STEP 100 tuiscriptadaptors UninstallStep c:\tswi\tinterpretsisinteg\scripts\ini.ini uSWI001-006

END_TESTCASE API-SEC-sistools-InterpretSIS-SWI001-0006
