//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
// @file tintsis.script
// Creation December 07, 2006
// interpretsis Integration Test Script
// Integration Test
// Component  : SWI
// Tests      : Ajay Bhandary
// The scope of this script is to compare the SWI and Interpretsis installation
// The ini file tintsis.ini is located at the path c:\tinterpretsisintg\testharness_preq1230\scripts\tintsis.script
//


PRINT Run test for installation of sis file 
LOAD_SUITE tbackuprestore
LOAD_SUITE tuiscriptadaptors
LOAD_SUITE tinterpretsis



//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		API-SEC-SWI-INTERPRETSIS-I003-0001
//! @SYMTestCaseDesc 		Compare installation of SWI and Interpretsis 
//! @SYMPREQ  			PREQ1230
//! @SYMTestStatus		3. Released
//! @SYMTestPriority 		Medium
//! @SYMTestActions 		backuprestore sis file.
//! @SYMTestExpectedResults 	Installation is successful     
//! @SYMTestType		CIT
//////////////////////////////////////////////////////////////////////////////////////////////

//Backup code in SWI is modified to return error for NR packages. So restore is also not possible.


START_TESTCASE API-SEC-SWI-INTERPRETSIS-I003-0001

RUN_TEST_STEP	100	tbackuprestore	PRESENT	c:\tswi\tinterpretsisinteg\scripts\ini.ini	I003A

RUN_TEST_STEP_RESULT -5	100	tbackuprestore	BACKUP	c:\tswi\tinterpretsisinteg\scripts\ini.ini	I003A
RUN_TEST_STEP	100	tbackuprestore	PRESENT	c:\tswi\tinterpretsisinteg\scripts\ini.ini	I003A

//RUN_TEST_STEP   100     tuiscriptadaptors ForceRemove   c:\tswi\tinterpretsisinteg\scripts\ini.ini I003removeregistrysisfile
//DELAY is given so that the backup.ctl file will be created in this time
//DELAY 5000
//RUN_TEST_STEP	100	tbackuprestore	ABSENT	c:\tswi\tinterpretsisinteg\scripts\ini.ini	I003A

//RUN_TEST_STEP	100	tbackuprestore	RESTORE	c:\tswi\tinterpretsisinteg\scripts\ini.ini	I003A
//RUN_TEST_STEP	100	tbackuprestore	PRESENT	c:\tswi\tinterpretsisinteg\scripts\ini.ini	I003A

//RUN_TEST_STEP   100     tuiscriptadaptors ForceRemove   c:\tswi\tinterpretsisinteg\scripts\ini.ini I003removeregistrysisfile
//DELAY 5000
//RUN_TEST_STEP	100	tbackuprestore	ABSENT	c:\tswi\tinterpretsisinteg\scripts\ini.ini	I003A

END_TESTCASE API-SEC-SWI-INTERPRETSIS-I003-0001


