//
// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
// @file tintsisscr001_db.script
// Creation October 2008
// Interpretsis Unit Test Script
//

/////////////////////////////////////////////////////////////////////////////////
LOAD_SUITE tuiscriptadaptors

//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		API-SEC-SWI-INTERPRETSIS-SCR-0001
//! @SYMTestCaseDesc 		Check values of 'Origin Verified' and 'Validation Status' when Interpretsis is invoked with out -f option.
//! @SYMPREQ  			PREQ1269
//! @SYMTestStatus		3. Released
//! @SYMTestPriority 		Medium
//! @SYMTestActions 		Check the value of 'origin verified' and 'validation status' in SCR
//! @SYMTestExpectedResults 	'Origin Verified' = 1 and 'validation status' = 50 (Trusted To Anchor)
//! @SYMTestType		ComponentUnitTest
//////////////////////////////////////////////////////////////////////////////////////////////
START_TESTCASE API-SEC-SWI-INTERPRETSIS-SCR-0001

RUN_TEST_STEP 100 tuiscriptadaptors CheckSCRFieldStep z:\tswi\tuiscriptadaptors\scripts\tswiregcompfields.ini originverified_true
RUN_TEST_STEP 100 tuiscriptadaptors CheckSCRCompPropertyStep z:\tswi\tuiscriptadaptors\scripts\tswiregcompfields.ini validationstatus_valid
RUN_TEST_STEP 100 tuiscriptadaptors ForceRemove z:\tswi\tuiscriptadaptors\scripts\tswiregcompfields.ini removebase_rctlfile

END_TESTCASE API-SEC-SWI-INTERPRETSIS-SCR-0001
