//
// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
// @file tintsisscr004_db.script
// Creation October 2008
// Interpretsis Unit Test Script
//

/////////////////////////////////////////////////////////////////////////////////
LOAD_SUITE tuiscriptadaptors

//////////////////////////////////////////////////////////////////////////////////////////////
//! @SYMTestCaseID 		API-SEC-SWI-INTERPRETSIS-SCR-0004
//! @SYMTestCaseDesc 		Check values of 'Hidden' field in SCR when Interpretsis installs an hidden component.
//! @SYMPREQ  			PREQ1269
//! @SYMTestStatus		3. Released
//! @SYMTestPriority 		Medium
//! @SYMTestActions 		Check the value of 'Hidden' field in SCR
//! @SYMTestExpectedResults 	'Hidden'= 1
//! @SYMTestType		ComponentUnitTest
//////////////////////////////////////////////////////////////////////////////////////////////
START_TESTCASE API-SEC-SWI-INTERPRETSIS-SCR-0004

RUN_TEST_STEP 100 tuiscriptadaptors CheckSCRFieldStep z:\tswi\tuiscriptadaptors\scripts\tswiregcompfields.ini hidden_true
RUN_TEST_STEP 100 tuiscriptadaptors ForceRemove z:\tswi\tuiscriptadaptors\scripts\tswiregcompfields.ini removehiddensactlfile

END_TESTCASE API-SEC-SWI-INTERPRETSIS-SCR-0004
