
#
# Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description: 
#


# Input
HEADERS +=./transport/inc/catalogshttpdownload.h \
					./transport/inc/catalogshttpdownloadmanagerimpl.h \

SOURCES += ./src/catalogsbasemessageimpl.cpp \
./src/catalogsclientserverserver.cpp \
./src/catalogsclientserverserversession.cpp \
./src/catalogsincompletemessage.cpp \
./src/catalogsserverengine.cpp \
./src/catalogsutils.cpp \
./src/catalogskeyvaluepair.cpp \
./src/catalogscontextimpl.cpp \
./src/catalogsbigdes.cpp \
./src/catalogsinterfacebase.cpp \
./src/catalogsinterfaceidentifier.cpp \
./src/catalogsstringmanager.cpp \
./src/catalogsshutdownoperation.cpp \
./transport/src/catalogstransportimpl.cpp \
./transport/src/catalogshttpconfigimpl.cpp \
./transport/src/catalogshttpheadersimpl.cpp \
./transport/src/catalogshttpsessionimpl.cpp \
./transport/src/catalogshttpdownloadmanagerimpl.cpp \
./transport/src/catalogshttpdownload.cpp \
./transport/src/catalogshttptransaction.cpp \
./transport/src/catalogshttptransactionmanagerimpl.cpp \
./transport/src/catalogshttpstack.cpp \
./transport/src/catalogshttpsessionmanagerimpl.cpp \
./transport/src/catalogshttpconnectioncreator.cpp \
./transport/src/catalogshttpconnectionmanager.cpp \
./transport/src/catalogssmssessionimpl.cpp \
./transport/src/catalogssmsoperationimpl.cpp \
./transport/src/catalogssmssender.cpp \
./transport/src/catalogssmsutils.cpp \
./transport/src/catalogsnetworkmanager.cpp \
./transport/src/catalogsconnectioneventsink.cpp \
./transport/src/catalogshttprequestparser.cpp \
./transport/src/catalogshttprequestadapter.cpp \
./transport/src/catalogshttpresponsecomposer.cpp \
./transport/src/catalogshttputils.cpp \
./transport/src/catalogsconnection.cpp \
./accesspointmanager/src/catalogsaccesspointmanagerimpl.cpp \
./accesspointmanager/src/catalogsaccesspoint.cpp \
./accesspointmanager/src/catalogsaccesspointsettings.cpp\
./accesspointmanager/src/catalogsaccesspointmap.cpp \
./accesspointmanager/src/catalogsclientaccesspointdata.cpp \
./accesspointmanager/src/catalogsremoveaccesspointshutdownoperation.cpp \
../provider/server/src/ncdcommunicable.cpp \
../provider/server/src/ncdproviderimpl.cpp \
../provider/server/src/ncdnodemanager.cpp \
../provider/server/src/ncdnodedbmanager.cpp \
../provider/server/src/ncdoperationmanager.cpp \
../provider/server/src/ncdnodeimpl.cpp \
../provider/server/src/ncdnodefolder.cpp \
../provider/server/src/ncdparentoftransparentnode.cpp \
../provider/server/src/ncdnodetransparentfolder.cpp \
../provider/server/src/ncdnodeitem.cpp \
../provider/server/src/ncdrootnode.cpp \
../provider/server/src/ncdnodemetadataimpl.cpp \
../provider/server/src/ncdnodeitemmetadata.cpp \
../provider/server/src/ncdnodefoldermetadata.cpp \
../provider/server/src/ncdnodedisclaimer.cpp \
../provider/server/src/ncdnodeiconimpl.cpp \
../provider/server/src/ncdnodescreenshotimpl.cpp \
../provider/server/src/ncdnodeskinimpl.cpp \
../provider/server/src/ncdnodelink.cpp \
../provider/server/src/ncdnodeitemlink.cpp \
../provider/server/src/ncdnodefolderlink.cpp \
../provider/server/src/ncdnodeidentifier.cpp \
../provider/server/src/ncdnodeuserdataimpl.cpp \
../provider/server/src/ncdnodedownloadimpl.cpp \
../provider/server/src/ncdnodeupgradeimpl.cpp \
../provider/server/src/ncdnodedependencyimpl.cpp \
../provider/server/src/ncdnodecachecleaner.cpp \
../provider/server/src/ncdnodecachecleanermanager.cpp \
../provider/server/src/ncdnodefactory.cpp \
../provider/server/src/ncdnodeidentifiereditor.cpp \
../provider/server/src/ncddbmaxsizemap.cpp \
../provider/server/src/ncdbaseoperation.cpp \
../provider/server/src/ncdloadnodeoperationimpl.cpp \
../provider/server/src/ncdloadrootnodeoperationimpl.cpp \
../provider/server/src/ncdsendableprogress.cpp \
../provider/server/src/ncdconfigurationmanagerimpl.cpp \
../provider/server/src/ncdpurchaseoperationimpl.cpp \
../provider/server/src/ncdpurchaseoptionimpl.cpp \
../provider/server/src/ncdserversubscription.cpp \
../provider/server/src/ncdserverpartofsubscription.cpp \
../provider/server/src/ncdserverupgrade.cpp \
../provider/server/src/ncdserversubscribablecontent.cpp \
../provider/server/src/ncdnodeinstallimpl.cpp \
../provider/server/src/ncdinstalloperationimpl.cpp \
../provider/server/src/ncdnodecontentinfoimpl.cpp \
../provider/server/src/ncdnodeuricontentimpl.cpp \
../provider/server/src/ncdinstallinfo.cpp \
../provider/server/src/ncdfileinfo.cpp \
../provider/server/src/ncdsubscriptionmanagerimpl.cpp \
../provider/server/src/ncdclientssubscriptions.cpp \
../provider/server/src/ncdsubscriptiongroup.cpp \
../provider/server/src/ncdsubscriptionimpl.cpp \
../provider/server/src/ncdsubscriptionoperationimpl.cpp \
../provider/server/src/ncdsubscriptionssourceidentifier.cpp \
../provider/server/src/ncdrightsobjectoperationimpl.cpp \
../provider/server/src/ncdnodepreviewimpl.cpp \
../provider/server/src/ncdserveraddress.cpp \
../provider/server/src/ncdsearchoperationimpl.cpp \
../provider/server/src/ncdsearchnodeitem.cpp \
../provider/server/src/ncdsearchnodefolder.cpp \
../provider/server/src/ncdsearchnodebundle.cpp \
../provider/server/src/ncdbundlefolder.cpp \
../provider/server/src/ncdpreviewmanager.cpp \
../provider/server/src/ncdchildentity.cpp \
../provider/server/src/ncdchildentitymap.cpp \
../provider/server/src/ncdsearchrootnode.cpp \
../provider/server/src/ncdproviderutils.cpp \
../provider/server/src/ncdserverdetailsimpl.cpp \
../provider/server/src/ncdcontentdescriptor.cpp \
../provider/server/src/ncdsubscriptiondatacompleter.cpp \
../provider/server/src/ncdnodesupplier.cpp \
../provider/server/src/ncdnodesupplierlink.cpp \
../provider/server/src/ncddownloadinfo.cpp \
../provider/server/src/ncdextendedinstallinfo.cpp \
../provider/server/src/ncdloadbundlenodeoperationimpl.cpp \
../provider/server/src/ncddependencyinfo.cpp \
../provider/server/src/ncdfavoritemanagerimpl.cpp \
../provider/server/src/ncdreportmanager.cpp \
../provider/server/src/ncdreport.cpp \
../provider/server/src/ncdreportdownload.cpp \
../provider/server/src/ncdreportomadownload.cpp \
../provider/server/src/ncdreportinstall.cpp \
../provider/server/src/ncdnodeseeninfo.cpp \
../provider/server/src/ncdnodeseenimpl.cpp \
../provider/server/src/ncdnodeseenfolderimpl.cpp \
../provider/server/src/ncdnodeidentifierutils.cpp \
../provider/server/src/ncdpurchasehistoryutils.cpp \
../provider/server/src/ncdcreateaccesspointoperationimpl.cpp \
../provider/server/src/ncdsendhttprequestoperationimpl.cpp \
../provider/server/src/ncdhttputils.cpp \
../provider/server/src/ncdserverreportoperationimpl.cpp \
../provider/server/src/ncdserverreportmanagerimpl.cpp \
../provider/server/src/ncdprovidermanager.cpp \
../provider/server/src/ncdgeneralmanager.cpp \
../provider/server/src/ncddownloadoperationimpl.cpp \
../provider/server/src/ncdbasedownloadhandler.cpp \
../provider/server/src/ncdskindownloadhandler.cpp \
../provider/server/src/ncdfilestoragefilehandler.cpp \
../provider/server/src/ncddatabasefilehandler.cpp \
../provider/server/src/ncdicondownloadhandler.cpp \
../provider/server/src/ncdfiledownloadhandler.cpp \
../provider/server/src/ncdpreviewdownloadhandler.cpp \
../provider/server/src/ncdscreenshotdownloadhandler.cpp \
../provider/server/src/ncdcontentdownloadoperation.cpp \
../provider/server/src/ncddownloadsuboperation.cpp \
../provider/server/src/ncddescriptordownloadsuboperation.cpp \
../provider/server/src/ncdconfigurationparser.cpp \
../provider/server/src/ncdengineconfigurationimpl.cpp \
../provider/client/src/ncdqueryimpl.cpp \
../provider/client/src/ncdqueryitemimpl.cpp \
../provider/client/src/ncdquerytextitemimpl.cpp \
../provider/client/src/ncdquerynumericitemimpl.cpp \
../provider/client/src/ncdqueryselectionitemimpl.cpp \
../provider/client/src/ncdquerypincodeitemimpl.cpp \
../provider/client/src/ncdqueryoptionimpl.cpp \
../provider/client/src/ncdexpirednode.cpp \
../provider/client/src/ncdlocalizerutils.cpp \
../provider/storage/src/ncdstoragemanagerimpl.cpp \
../provider/storage/src/ncdstorageimpl.cpp \
../provider/storage/src/ncdstorageclientimpl.cpp \
../provider/storage/src/ncddbstoragemanager.cpp \
../provider/storage/src/ncdstoragefiledataitem.cpp \
../provider/storage/src/ncdfilestorageimpl.cpp \
../provider/storage/src/ncdstoragebase.cpp \
../provider/storage/src/ncddatabasestorageimpl.cpp \
../provider/storage/src/ncdstoragedescriptordataitem.cpp \
../provider/protocol/src/ncdparserimpl.cpp \
../provider/protocol/src/ncdparserfactory.cpp \
../provider/protocol/src/ncdprotocoldefaultobserverimpl.cpp \
../provider/protocol/src/ncd_pp_iconimpl.cpp \
../provider/protocol/src/ncd_pp_skinimpl.cpp \
../provider/protocol/src/ncd_parser_pp_response.cpp \
../provider/protocol/src/ncd_parser_pp_entityref.cpp \
../provider/protocol/src/ncd_parser_pp_embeddeddata.cpp \
../provider/protocol/src/ncd_parser_pp_datablocks.cpp \
../provider/protocol/src/ncd_parser_pp_purchaseoption.cpp \
../provider/protocol/src/ncd_parser_pp_dataentity.cpp \
../provider/protocol/src/ncd_parser_pp_dataentitycontent.cpp \
../provider/protocol/src/ncd_parser_pp_entitydependency.cpp \
../provider/protocol/src/ncd_parser_pp_download.cpp \
../provider/protocol/src/ncd_parser_pp_rights.cpp \
../provider/protocol/src/ncd_parser_pp_information.cpp \
../provider/protocol/src/ncd_parser_pp_messages.cpp \
../provider/protocol/src/ncd_parser_pp_moreinfo.cpp \
../provider/protocol/src/ncd_parser_pp_purchase.cpp \
../provider/protocol/src/ncd_parser_pp_purchaseinformation.cpp \
../provider/protocol/src/ncd_parser_pp_purchaseprocessed.cpp \
../provider/protocol/src/ncd_parser_pp_purchaseentity.cpp \
../provider/protocol/src/ncd_parser_pp_payment.cpp \
../provider/protocol/src/ncd_parser_pp_expiredcacheddata.cpp \
../provider/protocol/src/ncd_parser_pp_subscriptionreport.cpp \
../provider/protocol/src/ncd_parser_pp_subscription.cpp \
../provider/protocol/src/ncd_parser_pp_subscriptiondetails.cpp \
../provider/protocol/src/ncd_parser_cp_actionrequest.cpp \
../provider/protocol/src/ncd_parser_cp_response.cpp \
../provider/protocol/src/ncd_parser_cp_capabilities.cpp \
../provider/protocol/src/ncd_parser_cp_clientconfiguration.cpp \
../provider/protocol/src/ncd_parser_cp_cookie.cpp \
../provider/protocol/src/ncd_parser_cp_detail.cpp \
../provider/protocol/src/ncd_parser_cp_details.cpp \
../provider/protocol/src/ncd_parser_cp_error.cpp \
../provider/protocol/src/ncd_parser_cp_query.cpp \
../provider/protocol/src/ncd_parser_cp_queryelement.cpp \
../provider/protocol/src/ncd_parser_cp_serverdetails.cpp \
../provider/protocol/src/ncd_pp_folderrefimpl.cpp \
../provider/protocol/src/ncd_pp_itemrefimpl.cpp \
../provider/protocol/src/ncd_pp_datablockimpl.cpp \
../provider/protocol/src/ncd_pp_dataentityimpl.cpp \
../provider/protocol/src/ncd_pp_dataentitycontentimpl.cpp \
../provider/protocol/src/ncd_pp_entitydependencyimpl.cpp \
../provider/protocol/src/ncd_pp_embeddeddataimpl.cpp \
../provider/protocol/src/ncd_pp_expiredcacheddataimpl.cpp \
../provider/protocol/src/ncd_pp_informationimpl.cpp \
../provider/protocol/src/ncd_pp_purchaseoptionimpl.cpp \
../provider/protocol/src/ncd_pp_subscriptionimpl.cpp \
../provider/protocol/src/ncd_pp_subscriptiondetailsimpl.cpp \
../provider/protocol/src/ncd_pp_downloadimpl.cpp \
../provider/protocol/src/ncd_pp_descriptorimpl.cpp \
../provider/protocol/src/ncd_pp_rightsimpl.cpp \
../provider/protocol/src/ncd_pp_purchaseimpl.cpp \
../provider/protocol/src/ncd_pp_purchaseinformationimpl.cpp \
../provider/protocol/src/ncd_pp_purchaseprocessedimpl.cpp \
../provider/protocol/src/ncd_pp_purchaseentityimpl.cpp \
../provider/protocol/src/ncd_pp_paymentimpl.cpp \
../provider/protocol/src/ncd_pp_smsdetailsimpl.cpp \
../provider/protocol/src/ncd_cp_actionrequestimpl.cpp \
../provider/protocol/src/ncd_cp_clientconfigurationimpl.cpp \
../provider/protocol/src/ncd_cp_cookieimpl.cpp \
../provider/protocol/src/ncd_cp_detailimpl.cpp \
../provider/protocol/src/ncd_cp_errorimpl.cpp \
../provider/protocol/src/ncd_pp_errorimpl.cpp \
../provider/protocol/src/ncd_cp_queryimpl.cpp \
../provider/protocol/src/ncd_cp_queryelementimpl.cpp \
../provider/protocol/src/ncd_cp_queryoptionimpl.cpp \
../provider/protocol/src/ncd_cp_queryresponseimpl.cpp \
../provider/protocol/src/ncd_cp_serverdetailsimpl.cpp \
../provider/protocol/src/ncdsubparser.cpp \ 
../provider/protocol/src/ncdtoplevelparser.cpp \
../provider/protocol/src/ncdunknownparser.cpp \
../provider/protocol/src/ncdprotocolutils.cpp \
../provider/protocol/src/ncdparserobserverbundleimpl.cpp \
../provider/protocol/src/ncdprotocolimpl.cpp \
../provider/protocol/src/ncdsessionhandler.cpp \
../provider/protocol/src/ncdstring.cpp \
../provider/protocol/src/ncdrequestgenerator.cpp \
../provider/protocol/src/ncdrequestbase.cpp \
../provider/protocol/src/ncdrequestbrowsesearch.cpp \
../provider/protocol/src/ncdrequestconfiguration.cpp \
../provider/protocol/src/ncdrequestconfigurationdata.cpp \
../provider/protocol/src/ncdrequestpurchase.cpp \
../provider/protocol/src/ncdrequestmanagesubscriptions.cpp \
../provider/protocol/src/ncdrequestinstallation.cpp \
../provider/purchasehistory/src/ncdpurchasehistorydbimpl.cpp \
../provider/src/ncdkeyvaluemap.cpp \
../provider/src/ncdpurchasedetails.cpp \
../provider/src/ncddelay.cpp