//
// Copyright (c) 2008-2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//


PRINT Run all of the SCR tests.

RUN_SCRIPT z:\tusif\tscrdatalayer\tscr_datalayer.script
RUN_SCRIPT z:\tusif\tscr\tscr_api.script
RUN_SCRIPT z:\tusif\tscr\tscr_versioning.script
RUN_SCRIPT z:\tusif\tscr\tscr_appreginfo.script
RUN_SCRIPT z:\tusif\tscr\tscrapparc.script

