//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of the License "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run all USIF integration tests

// Delete the SCR Database file
LOAD_SUITE tscr
RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file

LOAD_SUITE tUsifSuite

// ************************ Integration test cases ************************

//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0001
//! @SYMTestCaseDesc 		Getting information about a component
//! @SYMTestStatus 		3. Released
 
START_TESTCASE API-SEC-USIF-tsifintegration-0001

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoByFileName
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoByFileHandle
RUN_TEST_STEP !Result=-9 100 tUsifSuite SifGetComponentInfoStep z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoOverflowByFileName
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoByFileNameForUninstalledCompoundComponent
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoByFileHandleForUninstalledCompoundComponent

END_TESTCASE API-SEC-USIF-tsifintegration-0001


//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0002
//! @SYMTestCaseDesc 		Installation/uninstallation of a native component through SIF by file name/handle
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0002

// by file name
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini InstallByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
// by file handle
RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini InstallByFileHandle
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
// compound package by file name
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootPkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild0PkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild1PkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild2PkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild0Child0PkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini InstallCompoundComponentByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootPkgExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild0PkgExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild1PkgExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild2PkgExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild0Child0PkgExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootPkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootChild0PkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootChild1PkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootChild2PkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootChild0Child0PkgByNameAndVendor
// compound package by file handle
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootPkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild0PkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild1PkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild2PkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild0Child0PkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini InstallCompoundComponentByFileHandle
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootPkgExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild0PkgExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild1PkgExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild2PkgExistence
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRootChild0Child0PkgExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootPkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootChild0PkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootChild1PkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootChild2PkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRootChild0Child0PkgByNameAndVendor

END_TESTCASE API-SEC-USIF-tsifintegration-0002


//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0003
//! @SYMTestCaseDesc 		Generic browser installation by file name/handle
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0003

RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRefPackageNonExistence
RUN_TEST_STEP 100 tUsifSuite SifGenericBrowserInstallStep z:\tusif\tsifintegration\tsifintegration.ini GenericBrowserInstallRefPkgByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRefBasePackageExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRefPkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRefPackageNonExistence
RUN_TEST_STEP 100 tUsifSuite SifGenericBrowserInstallStep z:\tusif\tsifintegration\tsifintegration.ini GenericBrowserInstallRefPkgByFileHandle
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRefUpgradePackageExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallRefPkgByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyRefPackageNonExistence

END_TESTCASE API-SEC-USIF-tsifintegration-0003


//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0004
//! @SYMTestCaseDesc 		SCOMO install inactivate
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0004

RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini InstallInactiveByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyInactivePackageExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence

END_TESTCASE API-SEC-USIF-tsifintegration-0004


//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0007
//! @SYMTestCaseDesc 		Upgrade of a native component through SIF
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0007

RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini InstallByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageExistence
RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini UpgradeByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyUpgradePackageExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence

END_TESTCASE API-SEC-USIF-tsifintegration-0007

//! @SYMTestCaseID		API-SEC-USIF-tsifintegration-0008
//! @SYMTestCaseDesc		Incorrect Upgrade of a native component through SIF
//! @SYMTestStatus		3. Released
START_TESTCASE API-SEC-USIF-tsifintegration-0008
RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini InstallByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageExistence
RUN_TEST_STEP !Result=-10301 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini InvalidUpgradeByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallByNameAndVendor
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
END_TESTCASE API-SEC-USIF-tsifintegration-0008


//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0009
//! @SYMTestCaseDesc 		Asynchronous cancellation of native installation
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0009

RUN_TEST_STEP !Result=-3 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini AsynchronousCancelInstallByFileName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
RUN_TEST_STEP !Result=-3 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini AsynchronousCancelInstallByFileHandle
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence

END_TESTCASE API-SEC-USIF-tsifintegration-0009


// Ensure clean database before the following tests (0011 - 0020), as they rely on component ids starting from 1
// Get the component information for a new base(SA type) component when it wasn't installed on the device and check that
// the information retrieved is as expected.

//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0010
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0010

RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForNewNativeBaseCompByFileName
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForNewNativeBaseCompByFileHandle

END_TESTCASE API-SEC-USIF-tsifintegration-0010


// Get the base(SA type) component information when the same component was already installed on the device and check that 
// the information retrieved is as expected.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0011
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0011

RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file
RUN_TEST_STEP 100 tUsifSuite SifInstallStep            z:\tusif\tsifintegration\tsifintegration.ini InstallComponentInfoIntegByFileName
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForInstalledNativeBaseByFileName
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForInstalledNativeBaseByFileHandle
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep          z:\tusif\tsifintegration\tsifintegration.ini UninstallComponentInfoInteg

END_TESTCASE API-SEC-USIF-tsifintegration-0011


// Get the Upgrading(PU type) component information when the base(SA type) component was already installed on the device
// and check that the information retrieved is matching with the expected values.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0012
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0012

RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file
RUN_TEST_STEP 100 tUsifSuite SifInstallStep            z:\tusif\tsifintegration\tsifintegration.ini InstallComponentInfoIntegByFileName
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForUpgradeByFNWhenBaseInstalled
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep 	       z:\tusif\tsifintegration\tsifintegration.ini UninstallComponentInfoInteg

END_TESTCASE API-SEC-USIF-tsifintegration-0012


// Get the Upgrading(PU type) component information when the base(SA type) component was not installed on the device and 
// check that the install status in retrieved info results in base package missing.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0013
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0013

RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForUpgradeByFNWhenBaseMissing

END_TESTCASE API-SEC-USIF-tsifintegration-0013


// Get the Patch(SP type) component information when the base(SA type) component was already installed on the device
// and check that the information retrieved is matching with the expected values.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0014
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0014

RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file
RUN_TEST_STEP 100 tUsifSuite SifInstallStep            z:\tusif\tsifintegration\tsifintegration.ini InstallComponentInfoIntegByFileName
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForPatchByFNWhenBaseInstalled
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep 	       z:\tusif\tsifintegration\tsifintegration.ini UninstallComponentInfoInteg

END_TESTCASE API-SEC-USIF-tsifintegration-0014


// Get the Patch(SP type) component information when the base(SA type) component was not installed on the device and
// check that the install status in retrieved info results in base package missing.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0015
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0015

RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForPatchByFNWhenBaseMissing

END_TESTCASE API-SEC-USIF-tsifintegration-0015


// Get component information when the base component has a higher version
// and check that the install status in retrieved info results in ENewerVersionAlreadyInstalled.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0016
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0016

RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file
RUN_TEST_STEP 100 tUsifSuite SifInstallStep            z:\tusif\tsifintegration\tsifintegration.ini InstallComponentInfoIntegByFileName
RUN_TEST_STEP 100 tUsifSuite SifInstallStep            z:\tusif\tsifintegration\tsifintegration.ini InstallComponentInfoIntegUpgradeByFileName
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForUpgradeByFNWhenHigherInstalled
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep 	       z:\tusif\tsifintegration\tsifintegration.ini UninstallComponentInfoInteg

END_TESTCASE API-SEC-USIF-tsifintegration-0016


// Get the component information for the new base(SA type) package with User Grantable capabilities, signed by a trusted CA
// and check that the authenticity and userGrantableCapsBitMask in the retrieved info is equal to  EValidatedToAnchor(50) 
// and 98304 (ReadUserData & WriteUserData) respectively.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0017
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0017

RUN_TEST_STEP 100 tscr SCRDeleteDbFile z:\tusif\tscr\tscr.ini db_file
RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForBaseWithUserCapsByFileName

END_TESTCASE API-SEC-USIF-tsifintegration-0017


// Get the component information for the base(SA) component with an exe which doesn't have any cpability and 
// check that the retrieved info matches with the expected values.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0018
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0018

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForNoCapabilityBaseByFileName

END_TESTCASE API-SEC-USIF-tsifintegration-0018


// Check whether the get component info request is cancelable.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0019
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0019

RUN_TEST_STEP !Result=-3 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini CancelAsyncGetCompInfoRequestByFileName

END_TESTCASE API-SEC-USIF-tsifintegration-0019


// Get the component information for the base (SA type) package with the package name and vendor name are empty and 
// check that the retrieved info matches with the expected values.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0020
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0020

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoForEmptyNameAndVendor

END_TESTCASE API-SEC-USIF-tsifintegration-0020


// Get the component information for the set of embedded components in the order of EmbeddingBaseWithEXE->EmbeddedBaseWithUserCapsEXE and 
// check that the retrieved info matches with the expected values.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0021
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0021

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForEmbeddedWithExes

END_TESTCASE API-SEC-USIF-tsifintegration-0021


// Get the component information for the set of embedded components in the order of EmbeddingBase->Embedded1->Embedded2 and 
// check that the retrieved info matches with the expected values.
//! @SYMTestCaseID 		API-SEC-USIF-tsifintegration-0022
//! @SYMTestStatus 		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0022

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForEmbededNativePackages

END_TESTCASE API-SEC-USIF-tsifintegration-0022


// Get the component information for the set of embedded components in the order of EmbeddingBaseWithText->EmbeddedWithExe and
// check that the retrieved info matches with the expected values.
//! @SYMTestCaseID		API-SEC-USIF-tsifintegration-0023
//! @SYMTestStatus		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0023

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetCompInfoForEmbeddedWithTextAndInnerWithExe

END_TESTCASE API-SEC-USIF-tsifintegration-0023


// Get the component information for multiple files in a sis file, first file is text file and second is executable 
// check that the retrieved info matches with the expected values.
//! @SYMTestCaseID		API-SEC-USIF-tsifintegration-0024
//! @SYMTestStatus		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0024

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoWithMultipleFiles

END_TESTCASE API-SEC-USIF-tsifintegration-0024


// Get the component information for multiple files with extension in different case
// check that the retrieved info matches with the expected values.
//! @SYMTestCaseID		API-SEC-USIF-tsifintegration-0025
//! @SYMTestStatus		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0025

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoWithExtensionInDifferentCase

END_TESTCASE API-SEC-USIF-tsifintegration-0025


// Get the component information for sis file containing only one dll
// check that the retrieved info matches with the expected values.
//! @SYMTestCaseID		API-SEC-USIF-tsifintegration-0026
//! @SYMTestStatus		3. Released

START_TESTCASE API-SEC-USIF-tsifintegration-0026

RUN_TEST_STEP 100 tUsifSuite SifGetComponentInfoStep   z:\tusif\tsifintegration\tsifintegration.ini GetComponentInfoWithOnlyDll

END_TESTCASE API-SEC-USIF-tsifintegration-0026


// Slient installation : Self-signed package
START_TESTCASE API-SEC-USIF-tsifintegration-00027
// by file name
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
RUN_TEST_STEP !Result=-5 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini SilentInstallSelfSignedByName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
// by file handle
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
RUN_TEST_STEP !Result=-5 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini SilentInstallSelfSignedByHandle
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini VerifyPackageNonExistence
END_TESTCASE API-SEC-USIF-tsifintegration-00027

// Slient installation : Signed package
START_TESTCASE API-SEC-USIF-tsifintegration-00028
// by file name
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini SignedPkgNonExistence
RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini SilentInstallSignedByName
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini SignedPkgExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallSignedPkg
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini SignedPkgNonExistence
// by file handle
RUN_TEST_STEP 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini SilentInstallSignedByHandle
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini SignedPkgExistence
RUN_TEST_STEP 100 tUsifSuite SifUninstallStep z:\tusif\tsifintegration\tsifintegration.ini UninstallSignedPkg
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini SignedPkgNonExistence
END_TESTCASE API-SEC-USIF-tsifintegration-00028

// Slient installation : Signed package with less capabilities (Package needs some capabilities additional to the ones 
// granted by the certificate used to sign it)
START_TESTCASE API-SEC-USIF-tsifintegration-00029
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini SignedLessCapsNonExistence
RUN_TEST_STEP !Result=-5 100 tUsifSuite SifInstallStep z:\tusif\tsifintegration\tsifintegration.ini SignedLessCapsPkg
RUN_TEST_STEP 100 tUsifSuite SifCommonVerificationStep z:\tusif\tsifintegration\tsifintegration.ini SignedLessCapsNonExistence
END_TESTCASE API-SEC-USIF-tsifintegration-00029

// Wait 3 seconds in order to let the SIF server shutdown itself
DELAY 3000

PRINT Complate_te_Sif_Tests
